<?php
$this->layout('_studio');
$labels=['new'=>'Nova','contacted'=>'Contatada','qualified'=>'Qualificada','proposal_sent'=>'Proposta enviada','won'=>'Fechada','lost'=>'Perdida','archived'=>'Arquivada'];
$syndicIntro="Prezado(a) {$proposal->name},\n\nA Connect Condomínios agradece a oportunidade de apresentar uma solução personalizada para o {$proposal->condominium}. Nossa proposta foi estruturada para oferecer segurança, transparência e eficiência à gestão condominial.";
$syndicScope="Gestão administrativa e financeira;\nPrestação de contas organizada e transparente;\nApoio ao síndico, conselho e moradores;\nControle de fornecedores, contratos e obrigações;\nTecnologia e comunicação para simplificar a rotina do condomínio.";
$adminIntro="Prezado(a) {$proposal->name},\n\nApresentamos uma proposta de parceria para apoiar a operação da {$proposal->condominium}. A Connect Condomínios combina processos, tecnologia e atendimento especializado para ampliar a capacidade da administradora e padronizar a experiência dos condomínios atendidos.";
$adminScope="Plataforma centralizada para gestão da carteira;\nAutomação de rotinas administrativas e financeiras;\nIndicadores, relatórios e acompanhamento operacional;\nApoio à implantação e treinamento das equipes;\nComunicação integrada com síndicos e condomínios.";
?>
<section class="studio-page-head"><div><small><?= htmlspecialchars($proposal->protocol) ?></small><h2><?= htmlspecialchars($proposal->condominium) ?></h2><p>Solicitação recebida em <?= date('d/m/Y \à\s H:i',strtotime($proposal->created_at)) ?>.</p></div><a class="studio-btn" href="<?= url('/studio/proposals') ?>"><ion-icon name="arrow-back-outline"></ion-icon>Voltar</a></section>
<div class="studio-proposal-detail">
  <section class="studio-panel"><header><div><small>SOLICITANTE</small><h2><?= htmlspecialchars($proposal->name) ?></h2></div><span class="studio-proposal-status <?= htmlspecialchars($proposal->status) ?>"><?= $labels[$proposal->status]??$proposal->status ?></span></header>
    <dl><div><dt>E-mail</dt><dd><a href="mailto:<?= htmlspecialchars($proposal->email) ?>"><?= htmlspecialchars($proposal->email) ?></a></dd></div><div><dt>WhatsApp</dt><dd><a href="https://wa.me/55<?= preg_replace('/\D+/','',$proposal->whatsapp) ?>" target="_blank"><?= htmlspecialchars($proposal->whatsapp) ?></a></dd></div><div><dt>Condomínio</dt><dd><?= htmlspecialchars($proposal->condominium) ?></dd></div><div><dt>Unidades</dt><dd><?= (int)$proposal->units ?></dd></div><div><dt>Perfil</dt><dd><?= htmlspecialchars(ucfirst($proposal->profile)) ?></dd></div><div><dt>Origem</dt><dd><?= htmlspecialchars($proposal->source_url?:'Site') ?></dd></div></dl>
    <?php if($proposal->message):?><div class="studio-proposal-message"><strong>Necessidade informada</strong><p><?= nl2br(htmlspecialchars($proposal->message)) ?></p></div><?php endif;?>
  </section>
  <section class="studio-panel"><header><div><small>ACOMPANHAMENTO</small><h2>Atualizar proposta</h2></div><ion-icon name="git-branch-outline"></ion-icon></header>
    <form class="studio-form" method="post" action="<?= url('/studio/proposals/'.$proposal->id) ?>"><?= csrf_input() ?><input type="hidden" name="action" value="update"><label>Status<select name="status"><?php foreach($labels as $key=>$label):?><option value="<?= $key ?>" <?= $proposal->status===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><label>Responsável<select name="assigned_to"><option value="">Sem responsável</option><?php foreach($team as $member):?><option value="<?= (int)$member->id ?>" <?= (int)$proposal->assigned_to===(int)$member->id?'selected':'' ?>><?= htmlspecialchars($member->first_name.' '.$member->last_name) ?></option><?php endforeach;?></select></label><div class="studio-form-actions"><button class="studio-btn primary" type="submit"><ion-icon name="save-outline"></ion-icon>Salvar acompanhamento</button></div></form>
  </section>
</div>
<section class="studio-panel studio-proposal-reply"><header><div><small>RESPOSTA COMERCIAL</small><h2>Gerar proposta em PDF</h2><p>Revise os textos, gere uma prévia ou envie o documento ao solicitante.</p></div><ion-icon name="document-attach-outline"></ion-icon></header>
  <form class="studio-form" method="post" action="<?= url('/studio/proposals/'.$proposal->id) ?>" data-proposal-response><?= csrf_input() ?>
    <div class="studio-fields-two"><label>Modelo<select name="template_type" data-proposal-template><option value="syndic">Síndico e condomínio</option><option value="administrator">Administradora</option></select></label><label>Validade<input type="date" name="valid_until" min="<?= date('Y-m-d') ?>" value="<?= date('Y-m-d',strtotime('+15 days')) ?>" required></label></div>
    <label>Assunto<input name="subject" maxlength="255" value="Proposta de gestão para <?= htmlspecialchars($proposal->condominium) ?>" required></label>
    <label>Apresentação<textarea name="introduction" rows="5" required><?= htmlspecialchars($syndicIntro) ?></textarea></label>
    <label>Escopo<textarea name="scope" rows="7" required><?= htmlspecialchars($syndicScope) ?></textarea></label>
    <div class="studio-fields-two"><label>Condições comerciais<textarea name="commercial_terms" rows="5" placeholder="Ex.: honorários mensais, implantação e itens inclusos" required>Honorários mensais: R$ 0,00
Implantação: a combinar conforme diagnóstico inicial.</textarea></label><label>Forma de pagamento<textarea name="payment_terms" rows="5" placeholder="Ex.: vencimento todo dia 10">Vencimento mensal conforme data definida em contrato.</textarea></label></div>
    <label>Observações<textarea name="notes" rows="3" placeholder="Informações complementares, condições especiais ou próximos passos"></textarea></label>
    <div class="studio-form-actions"><button class="studio-btn" name="action" value="generate_pdf" type="submit"><ion-icon name="eye-outline"></ion-icon>Gerar PDF</button><button class="studio-btn primary" name="action" value="send_pdf" type="submit" onclick="return confirm('Gerar e enviar esta proposta para <?= htmlspecialchars($proposal->email,ENT_QUOTES) ?>?')"><ion-icon name="send-outline"></ion-icon>Gerar e enviar</button></div>
  </form>
</section>
<section class="studio-panel studio-proposal-history"><header><div><small>VERSÕES</small><h2>Respostas geradas</h2></div><span><?= count($responses) ?></span></header><div><?php if(!$responses):?><div class="studio-empty">Nenhuma proposta em PDF foi gerada.</div><?php endif;?><?php foreach($responses as $response):?><article><div><strong><?= htmlspecialchars($response->subject) ?></strong><small><?= $response->template_type==='administrator'?'Administradora':'Síndico e condomínio' ?> · <?= date('d/m/Y H:i',strtotime($response->created_at)) ?></small></div><span class="studio-proposal-status <?= htmlspecialchars($response->status) ?>"><?= ['generated'=>'PDF gerado','queued'=>'Na fila','sent'=>'Enviada','failed'=>'Falhou','draft'=>'Rascunho'][$response->status]??$response->status ?></span><?php if($response->pdf_path):?><a class="studio-icon-action" href="<?= url('/studio/proposal-response/'.$response->id.'/pdf') ?>" target="_blank" title="Abrir PDF"><ion-icon name="document-outline"></ion-icon></a><?php endif;?></article><?php endforeach;?></div></section>
<?php $this->start('scripts'); ?><script>const proposalTemplates={syndic:{intro:<?= json_encode($syndicIntro,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,scope:<?= json_encode($syndicScope,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>},administrator:{intro:<?= json_encode($adminIntro,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,scope:<?= json_encode($adminScope,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>}};document.querySelector('[data-proposal-template]')?.addEventListener('change',event=>{const form=event.target.closest('form'),content=proposalTemplates[event.target.value];if(!form||!content)return;form.elements.introduction.value=content.intro;form.elements.scope.value=content.scope});</script><?php $this->stop(); ?>
