<?php $this->layout('layouts/studio'); $channelMap=[]; foreach($channels as $channel){$channelMap[$channel->id]=$channel;} ?>
<section class="studio-page-header"><div><small>ATENDIMENTO</small><h2>Perguntas frequentes</h2><p>Organize respostas rápidas por canais e conecte conteúdos ao Suporte.</p></div><a class="studio-btn" href="<?= url('/suporte') ?>" target="_blank"><ion-icon name="open-outline"></ion-icon>Ver suporte</a></section>
<nav class="studio-notification-tabs studio-faq-tabs" aria-label="Áreas do FAQ"><a class="<?= $tab==='questions'?'active':'' ?>" href="<?= url('/operation/faqs?tab=questions') ?>"><ion-icon name="chatbubbles-outline"></ion-icon><span>Perguntas</span><small><?= count($questions) ?></small></a><a class="<?= $tab==='compose'?'active':'' ?>" href="<?= url('/operation/faqs?tab=compose') ?>"><ion-icon name="add-circle-outline"></ion-icon><span>Nova pergunta</span></a><a class="<?= $tab==='channels'?'active':'' ?>" href="<?= url('/operation/faqs?tab=channels') ?>"><ion-icon name="folder-open-outline"></ion-icon><span>Canais</span><small><?= count($channels) ?></small></a></nav>

<?php if($tab==='questions'):?>
<section class="studio-panel studio-content-list studio-faq-table"><header><div><h2>Perguntas cadastradas</h2><small>Respostas rápidas disponíveis no sistema</small></div></header><div class="studio-table-wrap"><table class="studio-table"><thead><tr><th>Pergunta</th><th>Canal</th><th>Ordem</th><th>Suporte</th><th class="studio-table-action">Ações</th></tr></thead><tbody><?php if(!$questions):?><tr><td colspan="5"><div class="studio-empty">Nenhuma pergunta cadastrada.</div></td></tr><?php endif;?><?php foreach($questions as $item):?><tr><td><div class="studio-content-item"><span class="studio-content-thumb"><ion-icon name="help-outline"></ion-icon></span><span><strong><?= htmlspecialchars($item->question) ?></strong><small><?= htmlspecialchars(mb_strimwidth(strip_tags($item->response),0,105,'...')) ?></small></span></div></td><td><span class="studio-role-badge"><?= htmlspecialchars($channelMap[$item->channel_id]->channel??'Sem canal') ?></span></td><td><?= (int)$item->order_by ?></td><td><?php if($item->support_link):?><a class="studio-faq-support" href="<?= htmlspecialchars($item->support_link) ?>" target="_blank"><ion-icon name="book-outline"></ion-icon>Abrir matéria</a><?php else:?><span class="studio-muted-text">Não vinculado</span><?php endif;?></td><td class="studio-table-action"><div class="studio-row-actions"><form action="<?= url('/operation/faqs?tab=questions') ?>" method="post" onsubmit="return confirm('Excluir esta pergunta?')"><?= csrf_input() ?><input type="hidden" name="action" value="delete_question"><input type="hidden" name="question_id" value="<?= $item->id ?>"><button title="Excluir"><ion-icon name="trash-outline"></ion-icon></button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>

<?php if($tab==='compose'):?>
<section class="studio-panel studio-faq-tab-form"><header><div><small>CONTEÚDO</small><h2>Adicionar pergunta</h2><p>Escreva uma resposta direta e vincule um tutorial quando precisar de mais detalhes.</p></div><ion-icon name="help-circle-outline"></ion-icon></header><form class="studio-form" action="<?= url('/operation/faqs?tab=compose') ?>" method="post"><?= csrf_input() ?><input type="hidden" name="action" value="question"><div class="studio-fields-two"><label>Canal<select name="channel_id" required><option value="">Selecione</option><?php foreach($channels as $channel):?><option value="<?= $channel->id ?>"><?= htmlspecialchars($channel->channel) ?></option><?php endforeach;?></select></label><label>Ordem<input type="number" min="1" name="order_by" value="1"></label></div><label>Pergunta<input name="question" minlength="5" required placeholder="Ex.: Como publico uma nova comunicação?"></label><label>Resposta<textarea name="response" rows="8" minlength="10" required></textarea></label><label>Matéria de suporte relacionada<select name="support_link"><option value="">Nenhuma</option><?php foreach($supportArticles as $article):?><option value="<?= url('/suporte/'.$article->category()->uri.'/'.$article->uri) ?>"><?= htmlspecialchars($article->title) ?></option><?php endforeach;?></select><small>Abre a explicação completa na Central de Suporte.</small></label><button class="studio-btn primary"><ion-icon name="add-circle-outline"></ion-icon>Adicionar pergunta</button></form></section>
<?php endif;?>

<?php if($tab==='channels'):?>
<div class="studio-faq-channel-layout"><section class="studio-panel studio-faq-tab-form"><header><div><small>ORGANIZAÇÃO</small><h2>Novo canal</h2><p>Agrupe as perguntas por assunto ou área do sistema.</p></div><ion-icon name="folder-open-outline"></ion-icon></header><form class="studio-form" action="<?= url('/operation/faqs?tab=channels') ?>" method="post"><?= csrf_input() ?><input type="hidden" name="action" value="channel"><label>Nome<input name="channel" minlength="3" required></label><label>Descrição<textarea name="description" rows="6" required></textarea></label><button class="studio-btn primary"><ion-icon name="folder-outline"></ion-icon>Criar canal</button></form></section><section class="studio-panel studio-faq-channel-list"><header><div><small>CANAIS</small><h2>Canais cadastrados</h2></div><span><?= count($channels) ?></span></header><div><?php if(!$channels):?><div class="studio-empty">Nenhum canal cadastrado.</div><?php endif;?><?php foreach($channels as $channel): $channelQuestions=$channel->questions()->count();?><article><i><ion-icon name="folder-outline"></ion-icon></i><div><strong><?= htmlspecialchars($channel->channel) ?></strong><p><?= htmlspecialchars($channel->description) ?></p><small><?= $channelQuestions ?> pergunta(s)</small></div><form action="<?= url('/operation/faqs?tab=channels') ?>" method="post" onsubmit="return confirm('Excluir este canal?')"><?= csrf_input() ?><input type="hidden" name="action" value="delete_channel"><input type="hidden" name="channel_id" value="<?= (int)$channel->id ?>"><button type="submit" <?= $channelQuestions?'disabled title="O canal possui perguntas"':'title="Excluir canal"' ?>><ion-icon name="trash-outline"></ion-icon></button></form></article><?php endforeach;?></div></section></div>
<?php endif;?>
