<?php $this->layout('layouts/studio'); $weekdays=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado']; $months=[1=>'janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro']; $today=$weekdays[(int)date('w')].', '.date('d').' de '.$months[(int)date('n')]; ?>
<section class="operation-page-head"><div><h1>Meu Dia</h1><p><?= htmlspecialchars($today) ?> · visão operacional de compromissos e tarefas</p></div><div class="operation-head-actions"><a class="operation-btn" href="<?= url('/operation/dash') ?>"><ion-icon name="grid-outline"></ion-icon>Dashboard</a><a class="operation-btn primary" href="<?= url('/operation/visits') ?>"><ion-icon name="add-outline"></ion-icon>Agendar visita</a></div></section>
<section class="operation-kpis">
 <?php foreach([['Compromissos',$appointmentsCount,'Hoje','calendar-outline','visits_today'],['Itens de checklist',$scheduledTasksCount,'Pendentes','checkbox-outline','checklist_pending'],['Para agendar',$toScheduleCount,'Próximos','time-outline',''],['Aguardando terceiros',$waitingThirdPartiesCount,'Retornos','hourglass-outline',''],['Visitas esta semana',$weeklyVisitsCount,'Programadas','business-outline','']] as [$label,$value,$note,$icon,$key]): ?><article><div><span><?= $label ?></span><strong <?= $key?'data-operation-count="'.$key.'"':'' ?>><?= (int)$value ?></strong><small><?= $note ?></small></div><i><ion-icon name="<?= $icon ?>"></ion-icon></i></article><?php endforeach; ?>
</section>
<section class="operation-alert-strip" aria-label="Atenções do dia"><a href="<?= url('/operation/issues') ?>"><ion-icon name="time-outline"></ion-icon><span><strong><?= (int)$overdueCount ?></strong> itens atrasados</span></a><a href="<?= url('/operation/chamados?priority=urgent') ?>"><ion-icon name="alert-circle-outline"></ion-icon><span><strong><?= (int)$criticalTicketsCount ?></strong> chamados críticos</span></a><a href="<?= url('/operation/demandas') ?>"><ion-icon name="person-remove-outline"></ion-icon><span><strong><?= (int)$unassignedDemandsCount ?></strong> demandas sem responsável</span></a></section>
<section class="operation-workspace">
 <article class="operation-column"><nav class="operation-tabs"><a class="active">Dia</a><a href="<?= url('/operation/agenda?view=week') ?>">Semana</a><a href="<?= url('/operation/agenda?view=list') ?>">Agenda</a><a href="<?= url('/operation/agenda?view=map') ?>">Mapa</a></nav><header><strong>Programação de hoje</strong><small><?= count($dayAgenda) ?> compromisso(s)</small></header><div class="operation-timeline"><?php if($dayAgenda): foreach($dayAgenda as $event): ?><a href="<?= url($event->source_url) ?>"><time><?= htmlspecialchars($event->time) ?></time><div><span><?= htmlspecialchars($event->source_type) ?> · <?= htmlspecialchars(str_replace('_',' ',$event->status)) ?></span><strong><?= htmlspecialchars($event->title) ?></strong><small><?= htmlspecialchars($event->condominium_name?:'Administradora') ?><?= $event->responsible_name?' · '.htmlspecialchars($event->responsible_name):'' ?></small></div></a><?php endforeach; else: ?><div class="operation-empty tall"><ion-icon name="calendar-clear-outline"></ion-icon><strong>Agenda livre hoje</strong><small>Adicione um compromisso para organizar o dia.</small></div><?php endif; ?></div><a class="operation-add" href="<?= url('/operation/agenda?new=1') ?>"><ion-icon name="add-outline"></ion-icon>Novo compromisso</a></article>
 <article class="operation-column"><nav class="operation-tabs"><a class="active">Para fazer (<?= count($pendingTasks) ?>)</a><a href="<?= url('/operation/issues') ?>">Todas</a></nav><header><strong>Prioridades operacionais</strong><small>Ordenadas por prazo</small></header><div class="operation-task-list"><?php if($pendingTasks): foreach($pendingTasks as $task): ?><a href="<?= url($task->source_url) ?>"><i><ion-icon name="<?= htmlspecialchars($task->icon) ?>"></ion-icon></i><div><span><?= htmlspecialchars($task->source_type) ?></span><strong><?= htmlspecialchars($task->title) ?></strong><small><?= htmlspecialchars($task->subtitle) ?></small></div><time><?= htmlspecialchars($task->due??'Sem prazo') ?></time></a><?php endforeach; else: ?><div class="operation-empty tall"><ion-icon name="checkmark-done-outline"></ion-icon><strong>Tudo em dia</strong><small>Não existem pendências abertas.</small></div><?php endif; ?></div><a class="operation-add" href="<?= url('/operation/issues') ?>"><ion-icon name="add-outline"></ion-icon>Nova pendência</a></article>
 <article class="operation-column operation-detail"><header><span><small>Visita em destaque</small><strong><?= htmlspecialchars($currentVisit->title??'Nenhuma visita hoje') ?></strong></span><?php if($currentVisit): ?><a href="<?= url('/operation/visits/'.$currentVisit->id) ?>">Abrir</a><?php endif; ?></header><?php if($currentVisit): ?><div class="operation-checklist"><article><i><ion-icon name="business-outline"></ion-icon></i><span><strong><?= htmlspecialchars($currentVisit->condominium) ?></strong><small><?= htmlspecialchars(str_replace('_',' ',$currentVisit->status)) ?></small></span></article><?php foreach($currentVisit->items as $item): ?><article><i><ion-icon name="<?= $item->result==='pending'?'ellipse-outline':'checkmark-circle-outline' ?>"></ion-icon></i><span><strong><?= htmlspecialchars($item->title) ?></strong><small><?= htmlspecialchars(str_replace('_',' ',$item->result)) ?></small></span></article><?php endforeach; ?></div><a class="operation-btn primary" href="<?= url('/operation/visits/'.$currentVisit->id) ?>"><ion-icon name="play-outline"></ion-icon>Acompanhar visita</a><?php else: ?><div class="operation-empty tall"><ion-icon name="clipboard-outline"></ion-icon><strong>Nenhuma visita selecionada</strong><small>As informações da próxima visita aparecerão aqui.</small></div><?php endif; ?></article>
</section>
<?php $this->start('scripts') ?><script>window.addEventListener('operation:updated',event=>{const counts=event.detail?.counts||{};document.querySelectorAll('[data-operation-count]').forEach(node=>{if(counts[node.dataset.operationCount]!==undefined)node.textContent=counts[node.dataset.operationCount]})});</script><?php $this->stop() ?>
