<?php $this->layout('_studio'); ?>
<section class="studio-stats studio-user-stats">
    <article><span>Total de usuários</span><strong><?= number_format((int)($stats->total ?? 0),0,',','.') ?></strong><small><ion-icon name="arrow-up-outline"></ion-icon>Base atual</small><i class="green"><ion-icon name="people-outline"></ion-icon></i></article>
    <article><span>Ativos</span><strong><?= number_format((int)($stats->active ?? 0),0,',','.') ?></strong><small><ion-icon name="arrow-up-outline"></ion-icon>Acesso confirmado</small><i class="green"><ion-icon name="checkmark-outline"></ion-icon></i></article>
    <article><span>Inativos</span><strong><?= number_format((int)($stats->inactive ?? 0),0,',','.') ?></strong><small class="down"><ion-icon name="arrow-down-outline"></ion-icon>Aguardando confirmação</small><i class="amber"><ion-icon name="time-outline"></ion-icon></i></article>
    <article><span>Administradores</span><strong><?= number_format((int)($stats->admins ?? 0),0,',','.') ?></strong><small><ion-icon name="arrow-up-outline"></ion-icon>Perfis de gestão</small><i><ion-icon name="shield-checkmark-outline"></ion-icon></i></article>
</section>
<section class="studio-panel studio-list-panel">
    <header><div><h2>Lista de usuários</h2></div><div class="studio-user-list-actions"><a class="studio-btn" href="<?= url('/studio/users?'.http_build_query(array_filter(['q'=>$search,'status'=>$statusFilter,'export'=>'csv']))) ?>"><ion-icon name="download-outline"></ion-icon>Exportar</a><a class="studio-btn primary" href="<?= url('/studio/user') ?>"><ion-icon name="add-outline"></ion-icon>Adicionar usuário</a></div></header>
    <div class="studio-table-wrap"><table class="studio-table studio-user-table"><thead><tr><th>Usuário</th><th>Função</th><th>Status</th><th>Último acesso</th><th>Sessões</th><th class="studio-table-action">Ações</th></tr></thead><tbody>
    <?php if(!$users): ?><tr><td colspan="6"><div class="studio-empty">Nenhum usuário corresponde aos filtros.</div></td></tr><?php endif; ?>
    <?php foreach($users as $item): ?><?php $role=$item->accessRole(); $roleSlug=$role->slug??'user'; $photo=$item->photo()?image($item->photo,120,120):null; $active=$item->status==='confirmed'; $activity=$activityMap[(int)$item->id]??null; $displayName=html_entity_decode($item->fullName(),ENT_QUOTES|ENT_HTML5,'UTF-8'); $initials=mb_strtoupper(mb_substr(html_entity_decode((string)$item->first_name,ENT_QUOTES|ENT_HTML5,'UTF-8'),0,1).mb_substr(html_entity_decode((string)$item->last_name,ENT_QUOTES|ENT_HTML5,'UTF-8'),0,1)); ?>
        <tr><td><div class="studio-person studio-person-detailed"><?php if($photo):?><img src="<?= $photo ?>" alt=""><?php else:?><span class="studio-person-avatar <?= htmlspecialchars($roleSlug) ?>"><?= htmlspecialchars($initials) ?></span><?php endif;?><div class="studio-person-copy"><strong><?= htmlspecialchars($displayName) ?></strong><small><?= htmlspecialchars(html_entity_decode((string)$item->email,ENT_QUOTES|ENT_HTML5,'UTF-8')) ?></small></div></div></td><td><span class="studio-role-badge <?= htmlspecialchars($roleSlug) ?>"><?= htmlspecialchars($role->name??'Não definido') ?></span></td><td><span class="studio-user-state <?= $active?'active':'inactive' ?>"><i></i><?= $active?'Ativo':'Inativo' ?></span></td><td><?= $activity?date_fmt($activity->last_access,'d/m/Y H:i'):'Sem registro' ?></td><td><?= (int)($activity->sessions??0) ?></td><td class="studio-table-action"><a class="studio-icon-action" href="<?= url('/studio/user/'.$item->id) ?>" title="Gerenciar usuário" aria-label="Gerenciar <?= htmlspecialchars($displayName) ?>"><ion-icon name="ellipsis-horizontal"></ion-icon></a></td></tr>
    <?php endforeach; ?></tbody></table></div>
    <footer class="studio-list-footer"><span>Mostrando <?= (int)$shown ?> de <?= (int)$totalFiltered ?> usuário(s)</span><?= $paginator ?></footer>
</section>
