<?php

declare(strict_types=1);

if (defined('MOVESOS_TEST_BOOTSTRAPPED')) {
    return;
}
define('MOVESOS_TEST_BOOTSTRAPPED', true);

require __DIR__ . '/prepare-environment.php';

require_once dirname(__DIR__) . '/vendor/autoload.php';

$schema = [
    "CREATE TABLE IF NOT EXISTS users (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        email VARCHAR(180) NOT NULL UNIQUE,
        document VARCHAR(30) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        level INT NOT NULL DEFAULT 1,
        status VARCHAR(30) NOT NULL DEFAULT 'confirmed',
        forget VARCHAR(255) NULL,
        photo VARCHAR(255) NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS access_roles (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(80) NOT NULL, slug VARCHAR(80) NOT NULL UNIQUE, level INT NOT NULL DEFAULT 10,
        description VARCHAR(255) NULL, is_system TINYINT(1) NOT NULL DEFAULT 1,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS access_permissions (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE, group_name VARCHAR(80) NOT NULL,
        description VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS access_role_permissions (
        role_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id),
        CONSTRAINT fk_test_rp_role FOREIGN KEY(role_id) REFERENCES access_roles(id) ON DELETE CASCADE,
        CONSTRAINT fk_test_rp_permission FOREIGN KEY(permission_id) REFERENCES access_permissions(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS access_user_roles (
        user_id INT UNSIGNED NOT NULL, role_id INT UNSIGNED NOT NULL, assigned_by INT UNSIGNED NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id),
        CONSTRAINT fk_test_ur_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_test_ur_role FOREIGN KEY(role_id) REFERENCES access_roles(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS access_user_overrides (
        user_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, effect ENUM('allow','deny') NOT NULL,
        assigned_by INT UNSIGNED NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY(user_id,permission_id),
        CONSTRAINT fk_test_uo_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_test_uo_permission FOREIGN KEY(permission_id) REFERENCES access_permissions(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS password_reset_tokens (
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL,
        token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME NULL,
        revoked_at DATETIME NULL, request_ip VARCHAR(45) NULL, created_at DATETIME NOT NULL,
        INDEX idx_test_reset_user_created(user_id,created_at), INDEX idx_test_reset_ip_created(request_ip,created_at),
        CONSTRAINT fk_test_reset_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS system_audit_logs (
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, users_id INT UNSIGNED NULL,
        action VARCHAR(30) NOT NULL, entity VARCHAR(100) NOT NULL, entity_id VARCHAR(50) NULL,
        description VARCHAR(255) NOT NULL, context_json LONGTEXT NULL, severity VARCHAR(20) NOT NULL DEFAULT 'info',
        ip VARCHAR(45) NULL, user_agent VARCHAR(255) NULL, url VARCHAR(255) NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS app_log (
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, incident_id VARCHAR(32) NULL, request_id VARCHAR(32) NULL,
        corporations_id INT UNSIGNED NULL, condominium_id INT UNSIGNED NULL, users_id INT UNSIGNED NULL,
        level VARCHAR(20) NOT NULL DEFAULT 'info', channel VARCHAR(80) NOT NULL DEFAULT 'application', event_type VARCHAR(100) NULL,
        code VARCHAR(100) NULL, ip VARCHAR(45) NULL, msg TEXT NOT NULL, exception_class VARCHAR(255) NULL,
        file VARCHAR(500) NULL, line INT UNSIGNED NULL, url VARCHAR(500) NULL, context_json LONGTEXT NULL, trace LONGTEXT NULL,
        user_agent VARCHAR(500) NULL, fingerprint CHAR(64) NULL, occurrences INT UNSIGNED NOT NULL DEFAULT 1,
        status VARCHAR(20) NOT NULL DEFAULT 'open', first_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
        last_seen_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, resolved_by INT UNSIGNED NULL, resolved_at TIMESTAMP NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_test_log_fingerprint(fingerprint), INDEX idx_test_log_status(status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS categories (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL UNIQUE,
        description TEXT NOT NULL, cover VARCHAR(255) NULL, type VARCHAR(50) NOT NULL DEFAULT 'post',
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS posts (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, author INT UNSIGNED NULL, category INT UNSIGNED NULL,
        title VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL UNIQUE, subtitle TEXT NOT NULL, content LONGTEXT NOT NULL,
        cover VARCHAR(255) NULL, video VARCHAR(50) NULL, views INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'draft',
        post_at TIMESTAMP NULL, deleted_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS pages (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, author INT UNSIGNED NULL, title VARCHAR(255) NOT NULL,
        uri VARCHAR(255) NOT NULL UNIQUE, content LONGTEXT NOT NULL, cover VARCHAR(255) NULL, video VARCHAR(50) NULL,
        views INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'draft', post_at TIMESTAMP NULL, deleted_at TIMESTAMP NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS faq_channels (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, channel VARCHAR(255) NOT NULL, description TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS faq_questions (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, channel_id INT UNSIGNED NOT NULL, question VARCHAR(255) NOT NULL,
        response TEXT NOT NULL, support_link VARCHAR(255) NULL, order_by INT UNSIGNED NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS support_categories (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(120) NOT NULL, uri VARCHAR(140) NOT NULL UNIQUE,
        description VARCHAR(255) NULL, icon VARCHAR(80) NOT NULL, position INT UNSIGNED NOT NULL DEFAULT 0,
        status VARCHAR(20) NOT NULL DEFAULT 'published', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS support_articles (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, category_id INT UNSIGNED NOT NULL, author_id INT UNSIGNED NULL,
        title VARCHAR(180) NOT NULL, uri VARCHAR(190) NOT NULL UNIQUE, summary VARCHAR(320) NOT NULL, content LONGTEXT NOT NULL,
        cover VARCHAR(255) NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', views INT UNSIGNED NOT NULL DEFAULT 0,
        helpful_yes INT UNSIGNED NOT NULL DEFAULT 0, helpful_no INT UNSIGNED NOT NULL DEFAULT 0, published_at DATETIME NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS notifications_categories (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL UNIQUE,
        description TEXT NOT NULL, cover VARCHAR(255) NULL, type VARCHAR(50) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS notification_messages (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, sender_id INT UNSIGNED NULL, title VARCHAR(255) NOT NULL,
        body TEXT NOT NULL, audience VARCHAR(30) NOT NULL, target_user_id INT UNSIGNED NULL, severity VARCHAR(20) NOT NULL,
        delivery_channels VARCHAR(20) NOT NULL DEFAULT 'system', link VARCHAR(255) NULL, status VARCHAR(20) NOT NULL,
        scheduled_at DATETIME NULL, expires_at DATETIME NULL, delivered_at DATETIME NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS notifications (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, message_id INT UNSIGNED NULL, source_log_id BIGINT UNSIGNED NULL,
        users_id INT UNSIGNED NOT NULL, category INT UNSIGNED NOT NULL, image VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL,
        body TEXT NULL, severity VARCHAR(20) NOT NULL DEFAULT 'info', link VARCHAR(255) NOT NULL, view INT NOT NULL DEFAULT 0,
        read_at DATETIME NULL, expires_at DATETIME NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS mail_queue (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, notification_message_id INT UNSIGNED NULL, proposal_response_id INT UNSIGNED NULL, source_log_id BIGINT UNSIGNED NULL,
        users_id INT UNSIGNED NULL, subject VARCHAR(255) NOT NULL, body TEXT NOT NULL, attachments_json LONGTEXT NULL, from_email VARCHAR(255) NOT NULL,
        from_name VARCHAR(255) NOT NULL, recipient_email VARCHAR(255) NOT NULL, recipient_name VARCHAR(255) NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'pending', scheduled_at DATETIME NULL, attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
        max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 3, last_attempt_at DATETIME NULL, next_attempt_at DATETIME NULL,
        error_message VARCHAR(500) NULL, failed_at DATETIME NULL, cancelled_at DATETIME NULL, sent_at TIMESTAMP NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS movesos_versions (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, product ENUM('web','app','studio','erp','support') NOT NULL,
        version VARCHAR(30) NOT NULL, name VARCHAR(120) NULL, notes TEXT NULL,
        status ENUM('current','archived') NOT NULL DEFAULT 'current', created_by INT UNSIGNED NULL,
        published_at DATETIME NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY uq_test_product_version(product,version), INDEX idx_test_product_status(product,status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS studio_calendar_events (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, description TEXT NULL,
        starts_at DATETIME NOT NULL, ends_at DATETIME NULL, type VARCHAR(20) NOT NULL DEFAULT 'meeting', status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
        assigned_to INT UNSIGNED NULL, created_by INT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS studio_support_tickets (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, protocol CHAR(12) NOT NULL UNIQUE, subject VARCHAR(180) NOT NULL, message TEXT NOT NULL,
        area VARCHAR(20) NOT NULL DEFAULT 'general', priority VARCHAR(20) NOT NULL DEFAULT 'medium', status VARCHAR(30) NOT NULL DEFAULT 'open',
        requester_id INT UNSIGNED NULL, assigned_to INT UNSIGNED NULL, created_by INT UNSIGNED NOT NULL, due_at DATETIME NOT NULL,
        resolved_at DATETIME NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    "CREATE TABLE IF NOT EXISTS studio_support_ticket_messages (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, ticket_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL,
        message TEXT NOT NULL, is_internal TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
];
foreach ($schema as $statement) {
    $pdo->exec($statement);
}
$pdo->exec("ALTER TABLE mail_queue
    ADD COLUMN IF NOT EXISTS proposal_response_id INT UNSIGNED NULL AFTER notification_message_id,
    ADD COLUMN IF NOT EXISTS attachments_json LONGTEXT NULL AFTER body");
$pdo->exec("ALTER TABLE movesos_versions MODIFY product ENUM('web','app','studio','erp','support') NOT NULL");
