<?php $this->layout('layouts/studio'); ?>
<section class="studio-page-header"><div><small>BLOG</small><h2>Artigos</h2><p>Crie, revise e publique o conteúdo do site.</p></div><div class="actions"><a class="studio-btn" href="<?= url('/operation/blog/categories') ?>"><ion-icon name="folder-outline"></ion-icon>Categorias</a><a class="studio-btn primary" href="<?= url('/operation/blog/post') ?>"><ion-icon name="add-outline"></ion-icon>Novo artigo</a></div></section>
<section class="studio-panel studio-content-list">
    <header><div><h2>Lista de artigos</h2><small>Conteúdos cadastrados no blog</small></div><form class="studio-list-filter ajax_off" action="<?= url('/operation/blog/home') ?>" method="post"><label><ion-icon name="search-outline"></ion-icon><input name="s" value="<?= htmlspecialchars($search) ?>" placeholder="Buscar por título"></label><button class="studio-btn" type="submit">Buscar</button></form></header>
    <div class="studio-table-wrap"><table class="studio-table studio-content-table"><thead><tr><th>Artigo</th><th>Categoria</th><th>Autor</th><th>Status</th><th>Publicação</th><th class="studio-table-action">Ações</th></tr></thead><tbody>
    <?php if (!$posts): ?><tr><td colspan="6"><div class="studio-empty">Nenhum artigo encontrado.</div></td></tr><?php endif; ?>
    <?php foreach ($posts as $item): $category=$item->category(); $author=$item->author(); ?><tr><td><div class="studio-content-item"><span class="studio-content-thumb" style="<?= $item->cover?'background-image:url('.image($item->cover,300).')':'' ?>"><ion-icon name="newspaper-outline"></ion-icon></span><span><strong><?= htmlspecialchars($item->title) ?></strong><small><?= htmlspecialchars(mb_strimwidth((string)$item->subtitle,0,85,'...')) ?></small></span></div></td><td><?= htmlspecialchars($category->title??'Sem categoria') ?></td><td><?= htmlspecialchars($author?->fullName()??'Sem autor') ?></td><td><span class="status <?= htmlspecialchars($item->status) ?>"><?= $item->status==='post'?'Publicado':($item->status==='draft'?'Rascunho':'Lixeira') ?></span></td><td><?= date_fmt($item->post_at,'d/m/Y H:i') ?></td><td class="studio-table-action"><div class="studio-row-actions"><a href="<?= url('/operation/blog/post/'.$item->id) ?>" title="Editar"><ion-icon name="create-outline"></ion-icon></a><form action="<?= url('/operation/blog/post') ?>" method="post" onsubmit="return confirm('Excluir este artigo?')"><?= csrf_input() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="post_id" value="<?= $item->id ?>"><button title="Excluir"><ion-icon name="trash-outline"></ion-icon></button></form></div></td></tr><?php endforeach; ?>
    </tbody></table></div><footer class="studio-content-list-footer"><?= $paginator ?></footer>
</section>
