<?php $this->layout('layouts/studio'); ?>
<?php $editing=!empty($targetUser); $roleName=$selectedRole->name??'Sem perfil'; $photo=$editing&&$targetUser->photo()?image($targetUser->photo,300,300):themeStudio('/assets/images/avatar.jpg','moves_studio'); ?>
<section class="studio-page-head"><div><small>MOVESOS · CONTROLE DE ACESSO</small><h2><?= $editing?'Perfil do usuário':'Novo usuário' ?></h2><p><?= $editing?'Dados pessoais, foto, perfil-base e permissões específicas.':'Cadastre a conta e escolha o perfil inicial.' ?></p></div><a class="studio-btn" href="<?= url('/studio/users') ?>"><ion-icon name="arrow-back-outline"></ion-icon>Voltar</a></section>
<?php if($editing): ?>
<section class="studio-user-hero"><div class="studio-user-identity"><img src="<?= $photo ?>" alt="<?= htmlspecialchars($targetUser->fullName()) ?>"><div><span class="studio-user-state <?= $targetUser->status==='confirmed'?'active':'inactive' ?>"><i></i><?= $targetUser->status==='confirmed'?'Ativo':'Inativo' ?></span><h2><?= htmlspecialchars($targetUser->fullName()) ?></h2><p><?= htmlspecialchars($targetUser->email) ?></p><small><ion-icon name="calendar-outline"></ion-icon>Membro desde <?= date_fmt($targetUser->created_at,'d/m/Y') ?></small></div></div><dl><div><dt>Perfil atual</dt><dd><?= htmlspecialchars($roleName) ?></dd></div><div><dt>Telefone</dt><dd><?= htmlspecialchars($targetUser->phone_cell?:'Não informado') ?></dd></div><div><dt>Identificador</dt><dd>#<?= (int)$targetUser->id ?></dd></div></dl><a class="studio-btn" href="#permissoes"><ion-icon name="shield-outline"></ion-icon>Gerenciar acessos</a></section>
<div class="studio-user-settings-layout"><nav class="studio-user-tabs" aria-label="Configurações do usuário"><button class="active" type="button" data-user-tab="profile"><ion-icon name="person-outline"></ion-icon><span><strong>Dados e foto</strong><small>Informações pessoais</small></span></button><button type="button" data-user-tab="address"><ion-icon name="location-outline"></ion-icon><span><strong>Endereço</strong><small>Localização principal</small></span></button><button type="button" data-user-tab="access"><ion-icon name="lock-closed-outline"></ion-icon><span><strong>Permissões</strong><small>Perfil e exceções</small></span></button></nav><div class="studio-user-settings-content">
<form class="studio-user-profile-form active" data-user-panel="profile" action="<?= url('/studio/user/'.$targetUser->id) ?>" method="post" enctype="multipart/form-data">
    <?= csrf_input() ?><input type="hidden" name="action" value="profile"><div class="studio-user-profile-grid">
    <section class="studio-panel" id="dados"><header><div><small>CADASTRO</small><h2>Informações pessoais</h2></div></header><div class="studio-form"><div class="studio-fields-two"><label>Nome *<input name="first_name" value="<?= htmlspecialchars($targetUser->first_name) ?>" required></label><label>Sobrenome *<input name="last_name" value="<?= htmlspecialchars($targetUser->last_name) ?>" required></label></div><div class="studio-fields-two"><label>E-mail *<input type="email" name="email" value="<?= htmlspecialchars($targetUser->email) ?>" required></label><label>Telefone<input class="mask-cell" name="phone_cell" value="<?= htmlspecialchars($targetUser->phone_cell) ?>"></label></div><div class="studio-fields-two"><label>CPF *<input class="mask-doc" name="document" value="<?= htmlspecialchars($targetUser->document) ?>" required></label><label>Data de nascimento<input type="date" name="datebirth" value="<?= htmlspecialchars((string)$targetUser->datebirth) ?>"></label></div><div class="studio-fields-two"><label>Gênero<select name="genre"><option value="uninformed">Não informado</option><option value="female" <?= $targetUser->genre==='female'?'selected':'' ?>>Feminino</option><option value="male" <?= $targetUser->genre==='male'?'selected':'' ?>>Masculino</option><option value="other" <?= $targetUser->genre==='other'?'selected':'' ?>>Outro</option></select></label><label>Status<select name="status"><option value="confirmed" <?= $targetUser->status==='confirmed'?'selected':'' ?>>Ativo</option><option value="registered" <?= $targetUser->status!=='confirmed'?'selected':'' ?>>Inativo</option></select></label></div></div></section>
    <section class="studio-panel studio-user-photo-panel" id="foto"><header><div><small>FOTO PRIVADA</small><h2>Foto do usuário</h2><p>Usada somente no perfil e nunca exibida na Biblioteca de Mídia.</p></div><ion-icon name="camera-outline"></ion-icon></header><div class="studio-user-photo-upload"><figure><img src="<?= $photo ?>" alt="Foto atual" data-user-photo-preview><span>Prévia</span></figure><label class="studio-user-photo-drop" data-user-photo-drop><ion-icon name="cloud-upload-outline"></ion-icon><strong>Arraste a foto ou clique para selecionar</strong><small>JPG, PNG ou WEBP · máximo 3 MB · formato quadrado recomendado</small><em data-user-photo-name>Nenhum novo arquivo selecionado</em><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" data-user-photo-input></label></div><footer><label class="studio-user-photo-remove"><input type="checkbox" name="remove_photo" value="1" data-user-photo-remove><span><ion-icon name="trash-outline"></ion-icon>Remover foto atual ao salvar</span></label></footer></section>
    </div><div class="studio-form-actions"><a class="studio-btn" href="<?= url('/studio/users') ?>">Cancelar</a><button class="studio-btn primary" type="submit">Salvar alterações</button></div>
</form>
<form class="studio-user-address-form" data-user-panel="address" id="endereco" action="<?= url('/studio/user/'.$targetUser->id) ?>" method="post">
    <?= csrf_input() ?><input type="hidden" name="action" value="address">
    <section class="studio-panel"><header><div><small>LOCALIZAÇÃO</small><h2>Endereço principal</h2><p>Este endereço fica vinculado ao cadastro do usuário.</p></div><ion-icon name="location-outline"></ion-icon></header><div class="studio-form"><div class="studio-fields-two"><label>Identificação<input name="description" maxlength="255" value="<?= htmlspecialchars($address->description??'Endereço principal') ?>" placeholder="Casa, trabalho ou endereço principal"></label><label>CEP *<input class="mask-zip" name="code" inputmode="numeric" maxlength="9" value="<?= htmlspecialchars($address->code??'') ?>" placeholder="00000-000" required></label></div><div class="studio-fields-three"><label>Rua *<input name="street" value="<?= htmlspecialchars($address->street??'') ?>" required></label><label>Número *<input name="number" value="<?= htmlspecialchars($address->number??'') ?>" required></label><label>Complemento<input name="complement" value="<?= htmlspecialchars($address->complement??'') ?>"></label><label>Bairro *<input name="district" value="<?= htmlspecialchars($address->district??'') ?>" required></label><label>Cidade *<input name="city" value="<?= htmlspecialchars($address->city??'') ?>" required></label><label>UF *<input name="state" maxlength="2" value="<?= htmlspecialchars($address->state??'') ?>" placeholder="MG" required></label></div></div></section>
    <div class="studio-form-actions"><button class="studio-btn primary" type="submit"><ion-icon name="save-outline"></ion-icon>Salvar endereço</button></div>
</form>
<?php endif; ?>
<form class="studio-access-form <?= $editing?'studio-user-panel':'' ?>" <?= $editing?'data-user-panel="access"':'' ?> id="permissoes" action="<?= $editing?url('/studio/user/'.$targetUser->id):url('/studio/user') ?>" method="post">
    <?= csrf_input() ?><input type="hidden" name="action" value="<?= $editing?'access':'create' ?>">
    <?php if(!$editing): ?><section class="studio-panel"><header><div><small>IDENTIFICAÇÃO</small><h2>Dados da conta</h2></div></header><div class="studio-form"><div class="studio-fields-two"><label>Nome *<input name="first_name" required></label><label>Sobrenome *<input name="last_name" required></label></div><div class="studio-fields-two"><label>E-mail *<input type="email" name="email" required></label><label>CPF *<input class="mask-doc" name="document" required></label></div><label>Senha inicial *<input type="password" name="password" minlength="8" required></label></div></section><?php endif; ?>
    <section class="studio-panel"><header><div><small>HIERARQUIA</small><h2>Perfil-base</h2></div></header><div class="studio-form"><label>Perfil<select name="role_id" required><?php foreach($roles as $role): ?><option value="<?= $role->id ?>" <?= ($selectedRole->id??null)==$role->id?'selected':'' ?>><?= htmlspecialchars($role->name) ?> — <?= htmlspecialchars($role->description) ?></option><?php endforeach; ?></select></label><p class="studio-access-help">O perfil concede um conjunto padrão. Use as exceções apenas quando uma função precisar ser liberada ou bloqueada individualmente.</p></div></section>
    <section class="studio-panel"><header><div><small>EXCEÇÕES INDIVIDUAIS</small><h2>Permissões específicas</h2></div><span class="status draft">Herdar é recomendado</span></header><div class="studio-permission-list"><?php $group=null; foreach($permissions as $permission): ?><?php if($group!==$permission->group_name):$group=$permission->group_name;?><h3><?= htmlspecialchars($group) ?></h3><?php endif; ?><article><div><strong><?= htmlspecialchars($permission->name) ?></strong><small><?= htmlspecialchars($permission->description) ?></small></div><select name="permissions[<?= htmlspecialchars($permission->slug) ?>]" aria-label="Permissão <?= htmlspecialchars($permission->name) ?>"><option value="inherit">Herdar do perfil</option><option value="allow" <?= ($overrides[$permission->slug]??null)==='allow'?'selected':'' ?> <?= !$user->can($permission->slug)?'disabled':'' ?>>Permitir individualmente</option><option value="deny" <?= ($overrides[$permission->slug]??null)==='deny'?'selected':'' ?>>Bloquear individualmente</option></select></article><?php endforeach; ?></div></section>
    <div class="studio-access-save"><span><ion-icon name="shield-checkmark-outline"></ion-icon>Alterações de acesso ficam registradas na auditoria.</span><button class="studio-btn primary" type="submit"><?= $editing?'Salvar acessos':'Criar usuário' ?></button></div>
</form>
<?php if($editing): ?></div></div><?php $this->start('scripts'); ?><script>const userTabs=document.querySelectorAll('[data-user-tab]');const userPanels=document.querySelectorAll('[data-user-panel]');const userPanelHash={profile:'#dados',address:'#endereco',access:'#permissoes'};const showUserPanel=name=>{userTabs.forEach(tab=>tab.classList.toggle('active',tab.dataset.userTab===name));userPanels.forEach(panel=>panel.classList.toggle('active',panel.dataset.userPanel===name));if(history.replaceState)history.replaceState(null,'',userPanelHash[name]||'#dados')};userTabs.forEach(tab=>tab.addEventListener('click',()=>showUserPanel(tab.dataset.userTab)));const initialUserPanel=Object.keys(userPanelHash).find(name=>userPanelHash[name]===location.hash);if(initialUserPanel)showUserPanel(initialUserPanel);</script><?php $this->end(); ?><?php endif; ?>
