-- MovesOS database naming convention
-- English, snake_case, plural resource names, without legacy app/access prefixes.
RENAME TABLE
    `access_permissions` TO `permissions`,
    `access_roles` TO `roles`,
    `access_role_permissions` TO `role_permissions`,
    `access_user_overrides` TO `user_permission_overrides`,
    `access_user_roles` TO `user_roles`,
    `app_accountable` TO `accountables`,
    `app_address` TO `addresses`,
    `app_categories` TO `financial_categories`,
    `app_condominium` TO `condominiums`,
    `app_corporations` TO `corporations`,
    `app_credit_cards` TO `credit_cards`,
    `app_invoices` TO `invoices`,
    `app_log` TO `system_logs`,
    `app_orders` TO `orders`,
    `app_owner` TO `ownerships`,
    `app_plans` TO `plans`,
    `app_session` TO `user_sessions`,
    `app_subscriptions` TO `subscriptions`,
    `app_units` TO `units`,
    `app_wallets` TO `wallets`,
    `brief` TO `testimonials`,
    `categories` TO `content_categories`,
    `categories_slide` TO `slide_categories`,
    `movesos_versions` TO `system_versions`,
    `notifications_categories` TO `notification_categories`,
    `report_access` TO `access_reports`,
    `report_online` TO `online_sessions`,
    `system_audit_logs` TO `audit_logs`;
