-- Tutoriais iniciais do MovesOS. Podem ser editados normalmente no Studio.
INSERT INTO support_articles (category_id,author_id,title,uri,summary,content,status,published_at) VALUES
((SELECT id FROM support_categories WHERE uri='primeiros-passos'),1,'Conhecendo o Dashboard do MovesOS','conhecendo-o-dashboard-do-movesos','Entenda os indicadores, atalhos e informações exibidas na tela inicial.',
'<h2>Visão geral</h2><p>O Dashboard reúne os principais números do site e atalhos para as tarefas mais utilizadas.</p><ol><li>Use os cartões superiores para acompanhar páginas, artigos, usuários e acessos.</li><li>Consulte os conteúdos recentes para encontrar alterações rapidamente.</li><li>Use as ações rápidas para criar páginas, matérias e abrir o site.</li></ol><h2>Menu lateral</h2><p>Clique no ícone do menu para recolher os textos e manter apenas os ícones. A escolha fica salva neste navegador.</p><h2>Busca e notificações</h2><p>A busca superior localiza conteúdos do sistema. O sino abre as notificações e o ícone de ajuda direciona para o tutorial relacionado à tela atual.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='primeiros-passos'),1,'Como criar e publicar um artigo','como-criar-e-publicar-um-artigo','Passo a passo para cadastrar categorias, escrever, revisar e publicar artigos no site.',
'<h2>Antes de começar</h2><p>Acesse <strong>Artigos</strong>. Se necessário, crie primeiro uma categoria.</p><ol><li>Clique em <strong>Novo artigo</strong>.</li><li>Informe título e resumo. O endereço amigável será sugerido automaticamente.</li><li>Escreva o conteúdo no editor e use o botão de imagem para incluir capturas ou ilustrações.</li><li>Escolha categoria, autor, data e imagem de capa.</li><li>Salve como rascunho para revisar ou publique para exibir no site.</li></ol><h2>Boas práticas</h2><p>Use títulos objetivos, parágrafos curtos, subtítulos e texto alternativo nas imagens. Confira a prévia antes de publicar.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='primeiros-passos'),1,'Como cadastrar uma página institucional','como-cadastrar-uma-pagina-institucional','Crie e mantenha páginas permanentes do site pelo Studio.',
'<h2>Criando a página</h2><ol><li>Acesse <strong>Páginas</strong> e clique em <strong>Nova página</strong>.</li><li>Informe o título e confirme o endereço amigável.</li><li>Adicione o conteúdo e a imagem de destaque quando necessário.</li><li>Escolha entre rascunho e publicada.</li><li>Salve e abra o site para conferir o resultado.</li></ol><p>Use páginas para conteúdos permanentes, como apresentação, serviços e documentos institucionais. Para notícias e materiais periódicos, use Artigos.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='primeiros-passos'),1,'Como usar a Biblioteca de Mídia','como-usar-a-biblioteca-de-midia','Veja imagens, consulte informações, copie URLs e exclua arquivos sem vínculo.',
'<h2>Consultando arquivos</h2><p>Acesse <strong>Mídia</strong> para ver as imagens do site. Clique em uma miniatura para abrir a visualização completa.</p><p>A modal informa nome, formato, MIME, tamanho, dimensões, data, caminho e onde a imagem está sendo utilizada.</p><h2>Exclusão segura</h2><p>O MovesOS impede a exclusão de arquivos usados em artigos, páginas, usuários, destaques ou configurações. Remova primeiro o vínculo e tente novamente.</p><h2>Reutilização</h2><p>Ao editar um conteúdo, escolha uma imagem já existente na biblioteca para evitar cópias desnecessárias.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='suporte-e-seguranca'),1,'Como organizar perguntas frequentes','como-organizar-perguntas-frequentes','Cadastre canais, perguntas, respostas e associe explicações completas do Suporte.',
'<h2>Organize por canal</h2><p>Crie canais para agrupar dúvidas do mesmo assunto. Depois, cadastre a pergunta, uma resposta curta e a ordem de exibição.</p><h2>Vincule uma matéria</h2><p>Quando a dúvida exigir uma explicação detalhada, selecione uma matéria de suporte relacionada. O usuário poderá abrir o tutorial diretamente a partir da resposta.</p><h2>Resposta curta, tutorial completo</h2><p>Mantenha o FAQ direto. Use as matérias para passos, imagens, alertas e explicações extensas.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='conta-e-acesso'),1,'Como gerenciar usuários, perfis e permissões','como-gerenciar-usuarios-perfis-e-permissoes','Entenda a hierarquia e personalize acessos sem perder a segurança.',
'<h2>Perfis disponíveis</h2><p>O MovesOS possui Desenvolvedor, Super administrador, Administrador do cliente, Gerente, Operador e Usuário.</p><ol><li>Acesse <strong>Usuários</strong> e selecione uma conta.</li><li>Escolha o perfil-base mais próximo da função da pessoa.</li><li>Use as exceções para liberar ou negar apenas recursos específicos.</li><li>Salve e confira o resumo das permissões.</li></ol><h2>Segurança</h2><p>Conceda somente os acessos necessários. Apenas desenvolvedores podem administrar recursos técnicos globais e atribuir o perfil de Desenvolvedor.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='suporte-e-seguranca'),1,'Como consultar relatórios e alterações recentes','como-consultar-relatorios-e-alteracoes-recentes','Acompanhe acessos, usuários online e ações administrativas registradas.',
'<h2>Relatórios</h2><p>A tela de Relatórios apresenta registros recentes de acesso e pessoas online. Use essas informações para acompanhar o uso geral do sistema.</p><h2>Alterações recentes</h2><p>Na Central de Notificações, usuários autorizados visualizam a trilha de auditoria com data, usuário, ação, área, registro e campos alterados.</p><p>A auditoria ajuda a entender o que aconteceu, mas dados sensíveis como senhas e tokens não são exibidos.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='suporte-e-seguranca'),1,'Como configurar o MovesOS e trocar temas','como-configurar-o-movesos-e-trocar-temas','Atualize dados do site, e-mail, integrações, temas e acesso aos módulos.',
'<h2>Configurações gerais</h2><p>Acesse <strong>Configurações</strong> para alterar identidade, domínio, contatos, endereço, redes sociais, e-mail e parâmetros do sistema.</p><h2>Temas e módulos</h2><p>O MovesOS identifica os temas válidos dentro da pasta container. Selecione os temas do site, aplicativo e ERP e salve.</p><p>Desenvolvedores também podem bloquear temporariamente Studio, ERP ou aplicativo para todos os demais usuários.</p><h2>Dados secretos</h2><p>Credenciais já configuradas não são exibidas. Deixe o campo vazio para manter o valor atual.</p>', 'published',NOW()),
((SELECT id FROM support_categories WHERE uri='suporte-e-seguranca'),1,'Como criar e manter matérias de suporte','como-criar-e-manter-materias-de-suporte','Cadastre categorias e tutoriais que aparecem no site e na ajuda contextual do MovesOS.',
'<h2>Categorias</h2><p>No menu <strong>Suporte</strong>, crie categorias com nome, descrição, ícone e ordem.</p><h2>Matérias</h2><ol><li>Clique em <strong>Nova matéria</strong>.</li><li>Preencha título, resumo e categoria.</li><li>Escreva o passo a passo no editor e adicione imagens das telas.</li><li>Salve como rascunho ou publique.</li></ol><h2>Ajuda contextual</h2><p>O ícone de ajuda presente no cabeçalho pesquisa automaticamente materiais relacionados à tela atual. Algumas áreas possuem vínculo direto com um tutorial específico.</p>', 'published',NOW())
ON DUPLICATE KEY UPDATE title=VALUES(title),summary=VALUES(summary),content=VALUES(content),status='published';
