<?php $this->layout('_studio'); ?>
<div class="mce_upload studio-mce-upload">
    <form action="<?= url('/studio/blog/image') ?>" method="post" enctype="multipart/form-data">
        <?= csrf_input() ?><ion-icon name="image-outline"></ion-icon><h3>Imagem para o conteúdo</h3><p>Envie JPG, PNG ou WebP. A imagem será inserida na posição atual do editor.</p><input type="file" name="image" accept="image/jpeg,image/png,image/webp" required><button class="studio-btn primary" type="submit">Enviar e inserir</button><button class="studio-btn" type="button" data-media-picker data-media-editor="post-content"><ion-icon name="images-outline"></ion-icon>Biblioteca</button><button class="studio-btn studio-mce-close" type="button">Cancelar</button>
    </form>
</div>
<section class="studio-page-head studio-editor-heading"><div><small>BLOG</small><h2><?= $post ? 'Editar artigo' : 'Novo artigo' ?></h2><p>Crie conteúdo otimizado, organize a publicação e acompanhe o resultado no site.</p></div><div class="actions"><?php if ($post && $post->status === 'post'): ?><a class="studio-btn" href="<?= url('/artigos/'.$post->uri) ?>" target="_blank"><ion-icon name="eye-outline"></ion-icon>Visualizar</a><?php endif; ?><a class="studio-btn" href="<?= url('/studio/blog/home') ?>">Voltar</a></div></section>
<form class="studio-form studio-post-editor" action="<?= url('/studio/blog/post'.($post ? '/'.$post->id : '')) ?>" method="post" enctype="multipart/form-data">
    <?= csrf_input() ?><input type="hidden" name="action" value="<?= $post ? 'update' : 'create' ?>">
    <div class="studio-post-layout">
        <section class="studio-panel studio-post-content">
            <label>Título do artigo *<input id="post-title" name="title" maxlength="140" minlength="5" value="<?= htmlspecialchars($post->title ?? '') ?>" placeholder="Um título claro e interessante" required><small><span data-title-count>0</span>/140 caracteres</small></label>
            <label>Endereço amigável<input id="post-uri" name="uri" maxlength="180" value="<?= htmlspecialchars($post->uri ?? '') ?>" placeholder="gerado-automaticamente-pelo-titulo"><small><?= url('/artigos/') ?><span data-uri-preview><?= htmlspecialchars($post->uri ?? 'titulo-do-artigo') ?></span></small></label>
            <label>Resumo *<textarea id="post-subtitle" name="subtitle" rows="4" maxlength="300" minlength="10" placeholder="Resumo exibido nas listagens e nos mecanismos de busca" required><?= htmlspecialchars($post->subtitle ?? '') ?></textarea><small><span data-subtitle-count>0</span>/300 caracteres</small></label>
            <label>Conteúdo *<textarea class="mce" id="post-content" name="content" rows="22" required><?= $post->content ?? '' ?></textarea></label>
            <div class="studio-reading-info"><ion-icon name="time-outline"></ion-icon><span>Tempo estimado: <strong data-reading-time><?= reading_time($post->content ?? '') ?></strong> min de leitura</span></div>
        </section>
        <aside class="studio-post-sidebar">
            <section class="studio-panel"><header><div><small>PUBLICAÇÃO</small><h2>Status e data</h2></div><span class="status <?= $post->status ?? 'draft' ?>"><?= ($post->status ?? 'draft') === 'post' ? 'Publicado' : 'Rascunho' ?></span></header><input type="hidden" name="status" value="<?= htmlspecialchars($post->status ?? 'draft') ?>"><label>Publicar em<input type="datetime-local" name="post_at" value="<?= date('Y-m-d\TH:i', strtotime($post->post_at ?? 'now')) ?>" required></label><div class="studio-publish-actions"><button class="studio-btn" type="submit" name="submit_status" value="draft">Salvar rascunho</button><button class="studio-btn primary" type="submit" name="submit_status" value="post"><?= $post && $post->status === 'post' ? 'Atualizar' : 'Publicar' ?></button></div></section>
            <section class="studio-panel"><header><div><small>ORGANIZAÇÃO</small><h2>Classificação</h2></div></header><label>Categoria *<select name="category" required><option value="">Selecione</option><?php foreach ($categories as $item): ?><option value="<?= $item->id ?>" <?= ($post->category ?? null) == $item->id ? 'selected' : '' ?>><?= htmlspecialchars(trim($item->title)) ?></option><?php endforeach; ?></select></label><a class="studio-inline-link" href="<?= url('/studio/blog/category') ?>"><ion-icon name="add-circle-outline"></ion-icon>Criar categoria</a><label>Autor *<select name="author" required><?php foreach ($authors as $item): ?><option value="<?= $item->id ?>" <?= ($post->author ?? $user->id) == $item->id ? 'selected' : '' ?>><?= htmlspecialchars($item->fullName()) ?></option><?php endforeach; ?></select></label></section>
            <section class="studio-panel"><header><div><small>DESTAQUE</small><h2>Imagem de capa</h2></div></header><input type="hidden" id="post-library-cover" name="library_cover"><label class="studio-cover-upload"><input id="post-cover" type="file" name="cover" accept="image/jpeg,image/png,image/webp"><span><ion-icon name="cloud-upload-outline"></ion-icon><strong>Enviar nova imagem</strong><small>JPG, PNG ou WebP</small></span></label><button class="studio-btn studio-media-pick" type="button" data-media-picker data-media-target="#post-library-cover" data-media-preview=".studio-post-cover-preview"><ion-icon name="images-outline"></ion-icon>Escolher da biblioteca</button><img class="studio-preview studio-post-cover-preview <?= empty($post->cover) ? 'is-empty' : '' ?>" src="<?= !empty($post->cover) ? image($post->cover, 600) : '' ?>" alt="Prévia da capa"></section>
            <section class="studio-panel"><header><div><small>MÍDIA</small><h2>Vídeo relacionado</h2></div></header><label>URL ou ID do YouTube<input name="video" value="<?= htmlspecialchars($post->video ?? '') ?>" placeholder="https://youtu.be/..."></label></section>
            <?php if ($post): ?><section class="studio-panel studio-danger-zone"><header><div><small>CUIDADO</small><h2>Excluir artigo</h2></div></header><p>Esta ação remove o artigo e sua imagem de capa.</p><button class="studio-btn danger" type="submit" name="action" value="delete" data-confirm-submit="Excluir este artigo permanentemente?">Excluir artigo</button><input type="hidden" name="post_id" value="<?= $post->id ?>"></section><?php endif; ?>
        </aside>
    </div>
</form>
<?php $this->start('scripts') ?><script>
(()=>{const title=document.querySelector('#post-title'),uri=document.querySelector('#post-uri'),subtitle=document.querySelector('#post-subtitle'),cover=document.querySelector('#post-cover'),preview=document.querySelector('.studio-post-cover-preview');const slug=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const update=()=>{document.querySelector('[data-title-count]').textContent=title.value.length;document.querySelector('[data-subtitle-count]').textContent=subtitle.value.length;if(!uri.dataset.changed)uri.value=slug(title.value);document.querySelector('[data-uri-preview]').textContent=uri.value||'titulo-do-artigo'};title?.addEventListener('input',update);subtitle?.addEventListener('input',update);uri?.addEventListener('input',()=>{uri.dataset.changed='1';uri.value=slug(uri.value);update()});cover?.addEventListener('change',()=>{const file=cover.files?.[0];if(file){preview.src=URL.createObjectURL(file);preview.classList.remove('is-empty')}});document.querySelector('.studio-mce-close')?.addEventListener('click',()=>{const modal=document.querySelector('.studio-mce-upload');if(modal)modal.style.display='none'});update();})();
</script><?php $this->stop() ?>
