<?php
$this->layout('layouts/studio');
$first = strtotime($month . '-01');
$start = (int)date('N', $first);
$days = (int)date('t', $first);
$byDay = [];
foreach ($events as $event) $byDay[(int)date('j', strtotime($event->starts_at))][] = $event;
$monthLabel = class_exists(\IntlDateFormatter::class)
    ? (new \IntlDateFormatter('pt_BR', \IntlDateFormatter::NONE, \IntlDateFormatter::NONE, date_default_timezone_get(), null, "MMMM 'de' yyyy"))->format($first)
    : date('m/Y', $first);
?>
<section class="studio-page-head organic-page-header"><div><p class="organic-eyebrow">Atendimento</p><h1 class="organic-page-title">Agenda</h1><p class="organic-page-description">Organize atendimentos, tarefas e compromissos do time em uma visão mensal.</p></div><button class="organic-btn organic-btn-primary" type="button" data-agenda-new><ion-icon name="add-outline"></ion-icon>Novo evento</button></section>
<form class="studio-agenda-filters organic-card ajax_off" method="get" action="<?= url('/studio/agenda') ?>">
    <input type="hidden" name="month" value="<?= htmlspecialchars($month) ?>">
    <label>Tipo<select class="organic-select" name="type"><option value="">Todos</option><?php foreach(['meeting'=>'Reunião','support'=>'Atendimento','task'=>'Tarefa','deadline'=>'Prazo'] as $value=>$label):?><option value="<?= $value ?>" <?= $typeFilter===$value?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
    <label>Status<select class="organic-select" name="status"><option value="">Todos</option><?php foreach(['scheduled'=>'Agendado','completed'=>'Concluído','cancelled'=>'Cancelado'] as $value=>$label):?><option value="<?= $value ?>" <?= $statusFilter===$value?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
    <label>Responsável<select class="organic-select" name="assigned_to"><option value="">Todos</option><?php foreach($users as $item):?><option value="<?= $item->id ?>" <?= $assignedFilter==$item->id?'selected':'' ?>><?= htmlspecialchars($item->fullName()) ?></option><?php endforeach;?></select></label>
    <button class="organic-btn" type="submit"><ion-icon name="filter-outline"></ion-icon>Aplicar</button>
    <?php if($typeFilter||$statusFilter||$assignedFilter):?><a class="organic-btn" href="<?= url('/studio/agenda?month='.$month) ?>">Limpar</a><?php endif;?>
</form>
<section class="organic-card studio-agenda"><header class="organic-card-header"><a class="organic-btn organic-btn-icon" href="<?= url('/studio/agenda?month='.date('Y-m',strtotime($month.'-01 -1 month'))) ?>" aria-label="Mês anterior"><ion-icon name="chevron-back-outline"></ion-icon></a><h2 class="organic-card-title"><?= htmlspecialchars(ucfirst($monthLabel)) ?></h2><a class="organic-btn organic-btn-icon" href="<?= url('/studio/agenda?month='.date('Y-m',strtotime($month.'-01 +1 month'))) ?>" aria-label="Próximo mês"><ion-icon name="chevron-forward-outline"></ion-icon></a></header>
<div class="studio-agenda-weekdays"><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span><span>Dom</span></div><div class="studio-agenda-grid">
<?php for($blank=1;$blank<$start;$blank++): ?><div class="studio-agenda-day is-empty" aria-hidden="true"></div><?php endfor; ?>
<?php for($day=1;$day<=$days;$day++): ?><div class="studio-agenda-day <?= date('Y-m-d')===$month.'-'.str_pad((string)$day,2,'0',STR_PAD_LEFT)?'is-today':'' ?>"><strong><?= $day ?></strong><?php foreach($byDay[$day]??[] as $event): ?><button type="button" class="studio-agenda-event <?= htmlspecialchars($event->type.' '.$event->status) ?>" title="<?= htmlspecialchars($event->title.($event->assigned_name?' · '.$event->assigned_name:'')) ?>" data-agenda-event='<?= htmlspecialchars(json_encode(['id'=>(int)$event->id,'title'=>$event->title,'description'=>$event->description,'starts_at'=>date('Y-m-d\TH:i',strtotime($event->starts_at)),'ends_at'=>$event->ends_at?date('Y-m-d\TH:i',strtotime($event->ends_at)):'','type'=>$event->type,'status'=>$event->status,'assigned_to'=>$event->assigned_to],JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8') ?>'><span><?= date('H:i',strtotime($event->starts_at)) ?></span><?= htmlspecialchars($event->title) ?></button><?php endforeach;?></div><?php endfor; ?>
</div></section>
<div class="organic-modal" id="agenda-event-modal" data-organic-modal aria-hidden="true"><div class="organic-modal-dialog"><header class="organic-modal-header"><h2 class="organic-modal-title" data-agenda-modal-title>Novo evento</h2><button class="organic-modal-close" type="button" data-agenda-close aria-label="Fechar">×</button></header><form class="organic-form organic-modal-body" action="<?= url('/studio/agenda') ?>" method="post"><?= csrf_input() ?><input type="hidden" name="action" value="save"><input type="hidden" name="event_id" value=""><label class="organic-form-group organic-label">Título<input class="organic-input" name="title" required></label><label class="organic-form-group organic-label">Descrição<textarea class="organic-textarea" name="description" rows="3"></textarea></label><div class="organic-grid organic-grid-2"><label class="organic-form-group organic-label">Início<input class="organic-input" type="datetime-local" name="starts_at" required></label><label class="organic-form-group organic-label">Fim<input class="organic-input" type="datetime-local" name="ends_at"></label></div><div class="organic-grid organic-grid-3"><label class="organic-form-group organic-label">Tipo<select class="organic-select" name="type"><option value="meeting">Reunião</option><option value="support">Atendimento</option><option value="task">Tarefa</option><option value="deadline">Prazo</option></select></label><label class="organic-form-group organic-label">Status<select class="organic-select" name="status"><option value="scheduled">Agendado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></label><label class="organic-form-group organic-label">Responsável<select class="organic-select" name="assigned_to"><option value="">Não definido</option><?php foreach($users as $item):?><option value="<?= $item->id ?>"><?= htmlspecialchars($item->fullName()) ?></option><?php endforeach;?></select></label></div><footer class="organic-modal-footer"><button class="organic-btn organic-btn-danger" type="submit" name="action" value="delete" data-agenda-delete hidden data-confirm-submit="Excluir este compromisso?">Excluir</button><button class="organic-btn" type="button" data-agenda-close>Cancelar</button><button class="organic-btn organic-btn-primary">Salvar evento</button></footer></form></div></div>
<?php $this->start('scripts') ?><script>
(()=>{const modal=document.querySelector('#agenda-event-modal'),form=modal?.querySelector('form'),title=modal?.querySelector('[data-agenda-modal-title]'),deleteButton=modal?.querySelector('[data-agenda-delete]');const instance=()=>window.Organic?.Modal?.get(modal);const close=()=>instance()?.close();const open=data=>{form.reset();form.event_id.value=data?.id||'';form.title.value=data?.title||'';form.description.value=data?.description||'';form.starts_at.value=data?.starts_at||'<?= date('Y-m-d\TH:i') ?>';form.ends_at.value=data?.ends_at||'';form.type.value=data?.type||'meeting';form.status.value=data?.status||'scheduled';form.assigned_to.value=data?.assigned_to||'';title.textContent=data?.id?'Editar evento':'Novo evento';deleteButton.hidden=!data?.id;instance()?.open()};document.querySelector('[data-agenda-new]')?.addEventListener('click',()=>open());document.querySelectorAll('[data-agenda-event]').forEach(button=>button.addEventListener('click',()=>open(JSON.parse(button.dataset.agendaEvent))));modal?.querySelectorAll('[data-agenda-close]').forEach(button=>button.addEventListener('click',close));modal?.addEventListener('click',event=>{if(event.target===modal)close()})})();
</script><?php $this->stop() ?>
