<?php $this->layout('layouts/studio'); ?>
<section class="studio-page-header"><div><p class="studio-eyebrow">Sistema</p><h1 class="studio-page-title">Usuários</h1><p class="studio-page-description">Gerencie usuários, acessos, permissões e atividades do sistema.</p></div><div class="studio-page-actions"><a class="studio-btn primary" href="<?= url($adminBase . '/user') ?>"><ion-icon name="add-outline"></ion-icon>Novo usuário</a></div></section>
<section class="studio-dashboard-kpis" aria-label="Indicadores de usuários">
<?php foreach ([['Usuários',$stats->total??0,'contas cadastradas','people-outline',url($adminBase.'/users')],['Ativos',$stats->active??0,'acessos confirmados','checkmark-circle-outline',url($adminBase.'/users?status=confirmed')],['Inativos',$stats->inactive??0,'sem acesso ativo','pause-circle-outline',url($adminBase.'/users?status=registered')],['Administradores',$stats->admins??0,'perfis de gestão','shield-checkmark-outline','#lista-usuarios']] as [$label,$value,$note,$icon,$href]): ?><a class="studio-panel" href="<?= $href ?>"><i><ion-icon name="<?= $icon ?>"></ion-icon></i><div><span><?= $label ?></span><strong><?= number_format((int)$value,0,',','.') ?></strong><small><?= $note ?></small></div></a><?php endforeach; ?>
</section>
<section class="studio-panel studio-user-filters"><form class="studio-form" action="<?= url($adminBase.'/users') ?>" method="get"><div class="studio-filter-grid">
<label class="studio-search-field"><span>Buscar</span><span class="studio-input-icon"><ion-icon name="search-outline"></ion-icon><input type="search" name="q" value="<?= htmlspecialchars((string)$search) ?>" placeholder="Buscar por nome, e-mail ou documento"></span></label>
<label><span>Status</span><select name="status"><option value="">Todos</option><option value="confirmed" <?= $statusFilter==='confirmed'?'selected':'' ?>>Ativo</option><option value="registered" <?= $statusFilter==='registered'?'selected':'' ?>>Inativo</option></select></label>
<label><span>Perfil</span><select name="role"><option value="">Todos</option><?php foreach($roles as $role): ?><option value="<?= (int)$role->id ?>" <?= (int)$roleFilter===(int)$role->id?'selected':'' ?>><?= htmlspecialchars($role->name) ?></option><?php endforeach; ?></select></label>
<label><span>Ordenar por</span><select name="sort"><option value="name" <?= $sort==='name'?'selected':'' ?>>Nome</option><option value="created" <?= $sort==='created'?'selected':'' ?>>Data de cadastro</option><option value="access" <?= $sort==='access'?'selected':'' ?>>Último acesso</option><option value="status" <?= $sort==='status'?'selected':'' ?>>Status</option></select></label>
<label><span>Criado a partir de</span><input type="date" name="created_from" value="<?= htmlspecialchars($createdFrom) ?>"></label><label><span>Criado até</span><input type="date" name="created_to" value="<?= htmlspecialchars($createdTo) ?>"></label>
</div><div class="studio-form-actions"><button class="studio-btn primary" type="submit"><ion-icon name="funnel-outline"></ion-icon>Aplicar filtros</button><a class="studio-btn ghost" href="<?= url($adminBase.'/users') ?>">Limpar</a></div></form></section>
<section class="studio-panel studio-list-panel" id="lista-usuarios"><header><div><h2>Lista de usuários</h2><p><?= $totalFiltered?'Contas encontradas com os filtros atuais.':'Nenhuma conta encontrada.' ?></p></div><div class="studio-user-list-actions"><a class="studio-btn" href="<?= url($adminBase.'/users?'.http_build_query(array_filter(['q'=>$search,'status'=>$statusFilter,'role'=>$roleFilter,'created_from'=>$createdFrom,'created_to'=>$createdTo,'sort'=>$sort,'export'=>'csv']))) ?>"><ion-icon name="download-outline"></ion-icon>Exportar</a></div></header>
<form class="studio-user-bulk" action="<?= url($adminBase.'/users') ?>" method="post"><?= csrf_input() ?><div class="studio-bulk-toolbar" hidden data-user-bulk-toolbar><strong><span data-user-selected-count>0</span> selecionado(s)</strong><select name="action" aria-label="Ação em lote" required><option value="">Escolha uma ação</option><option value="bulk_activate">Ativar</option><option value="bulk_deactivate">Desativar</option><option value="bulk_delete">Excluir</option></select><button class="studio-btn primary" type="submit">Aplicar</button></div>
<div class="studio-table-wrap"><table class="studio-table studio-user-table"><thead><tr><th class="studio-check-cell"><input type="checkbox" data-user-select-all aria-label="Selecionar todos"></th><th>Usuário</th><th>Perfil</th><th>Status</th><th>Último acesso</th><th>Criado em</th><th class="studio-table-action">Ações</th></tr></thead><tbody>
<?php if(!$users): ?><tr><td colspan="7"><div class="studio-empty"><ion-icon name="people-outline"></ion-icon><strong><?= $search||$statusFilter||$roleFilter||$createdFrom||$createdTo?'Nenhum usuário corresponde aos filtros selecionados.':'Nenhum usuário encontrado.' ?></strong></div></td></tr><?php endif; ?>
<?php foreach($users as $item): $role=$item->accessRole();$roleSlug=$role->slug??'user';$photo=$item->photo()?image($item->photo,120,120):null;$active=$item->status==='confirmed';$activity=$activityMap[(int)$item->id]??null;$displayName=html_entity_decode($item->fullName(),ENT_QUOTES|ENT_HTML5,'UTF-8');$initials=mb_strtoupper(mb_substr(html_entity_decode((string)$item->first_name,ENT_QUOTES|ENT_HTML5,'UTF-8'),0,1).mb_substr(html_entity_decode((string)$item->last_name,ENT_QUOTES|ENT_HTML5,'UTF-8'),0,1)); ?>
<tr><td class="studio-check-cell"><input type="checkbox" name="user_ids[]" value="<?= (int)$item->id ?>" data-user-select <?= (int)$item->id===1||(int)$item->id===(int)$user->id?'disabled':'' ?> aria-label="Selecionar <?= htmlspecialchars($displayName) ?>"></td><td><div class="studio-person studio-person-detailed"><?php if($photo):?><img src="<?= $photo ?>" alt=""><?php else:?><span class="studio-person-avatar <?= htmlspecialchars($roleSlug) ?>"><?= htmlspecialchars($initials) ?></span><?php endif;?><div class="studio-person-copy"><strong><?= htmlspecialchars($displayName) ?></strong><small><?= htmlspecialchars(html_entity_decode((string)$item->email,ENT_QUOTES|ENT_HTML5,'UTF-8')) ?></small></div></div></td><td><span class="studio-role-badge <?= htmlspecialchars($roleSlug) ?>"><?= htmlspecialchars($role->name??'Não definido') ?></span></td><td><span class="studio-user-state <?= $active?'active':'inactive' ?>"><i></i><?= $active?'Ativo':'Inativo' ?></span></td><td><?= $activity?date_fmt($activity->last_access,'d/m/Y H:i'):'Sem registro' ?></td><td><?= date_fmt($item->created_at,'d/m/Y') ?></td><td class="studio-table-action"><details class="studio-action-menu"><summary aria-label="Ações de <?= htmlspecialchars($displayName) ?>"><ion-icon name="ellipsis-horizontal"></ion-icon></summary><nav><a href="<?= url($adminBase.'/user/'.$item->id) ?>">Visualizar</a><a href="<?= url($adminBase.'/user/'.$item->id.'#dados') ?>">Editar</a><a href="<?= url($adminBase.'/user/'.$item->id.'#permissoes') ?>">Permissões</a></nav></details></td></tr><?php endforeach; ?></tbody></table></div></form>
<footer class="studio-list-footer"><span>Mostrando <?= (int)$shown ?> de <?= (int)$totalFiltered ?> usuário(s)</span><?= $paginator ?></footer></section>
<?php $this->start('scripts'); ?><script>const userChecks=[...document.querySelectorAll('[data-user-select]')],userAll=document.querySelector('[data-user-select-all]'),userToolbar=document.querySelector('[data-user-bulk-toolbar]'),userCount=document.querySelector('[data-user-selected-count]');const updateUserSelection=()=>{const count=userChecks.filter(input=>input.checked).length;if(userCount)userCount.textContent=count;if(userToolbar)userToolbar.hidden=count===0;if(userAll){const enabled=userChecks.filter(input=>!input.disabled);userAll.checked=enabled.length>0&&enabled.every(input=>input.checked);userAll.indeterminate=count>0&&!userAll.checked}};userAll?.addEventListener('change',()=>{userChecks.forEach(input=>{if(!input.disabled)input.checked=userAll.checked});updateUserSelection()});userChecks.forEach(input=>input.addEventListener('change',updateUserSelection));</script><?php $this->end(); ?>
