<?php

$route->namespace("Source\\Controllers\\Operation");
$route->group("/operation");

$route->get("/", "Operation:root");
$route->get("/login", "Operation:login");
$route->post("/login", "Operation:login");
$route->get("/sair", "Operation:logout");
$route->get("/logoff", "Operation:logout");

$route->get("/dash", "Operation:dash");
$route->get("/meu-dia", "Operation:meuDia");
$route->get("/realtime", "Operation:realtime");
$route->get("/condominiums", "Operation:condominiums");
$route->get("/condominiums/{id}", "Operation:condominiums");
$route->post("/condominiums", "Operation:condominiums");
$route->post("/condominiums/{id}", "Operation:condominiums");
$route->get("/condominios", "Operation:condominiums");
$route->get("/condominios/{id}", "Operation:condominiums");
$route->post("/condominios", "Operation:condominiums");
$route->post("/condominios/{id}", "Operation:condominiums");
$route->get("/demandas", "Operation:demands");
$route->get("/demandas/{id}", "Operation:demands");
$route->post("/demandas", "Operation:demands");
$route->post("/demandas/{id}", "Operation:demands");
$route->get("/demands", "Operation:demands");
$route->get("/demands/{id}", "Operation:demands");
$route->post("/demands", "Operation:demands");
$route->post("/demands/{id}", "Operation:demands");
$route->get("/visits", "Operation:visits");
$route->get("/visits/{id}", "Operation:visits");
$route->post("/visits", "Operation:visits");
$route->post("/visits/{id}", "Operation:visits");
$route->get("/visitas/{id}/relatorio", "Operation:visitReport");
$route->get("/visitas/{id}", "Operation:visits");
$route->get("/checklists", "Operation:checklists");
$route->get("/checklists/{id}", "Operation:checklists");
$route->post("/checklists", "Operation:checklists");
$route->post("/checklists/{id}", "Operation:checklists");
$route->get("/issues", "Operation:issues");
$route->get("/issues/{id}", "Operation:issues");
$route->post("/issues", "Operation:issues");
$route->post("/issues/{id}", "Operation:issues");
$route->get("/action-plans", "Operation:actionPlans");
$route->get("/action-plans/{id}", "Operation:actionPlans");
$route->post("/action-plans", "Operation:actionPlans");
$route->post("/action-plans/{id}", "Operation:actionPlans");
$route->get("/assets", "Operation:assets");
$route->get("/assets/{id}", "Operation:assets");
$route->post("/assets", "Operation:assets");
$route->post("/assets/{id}", "Operation:assets");
$route->get("/requests", "Operation:residentRequests");
$route->get("/requests/{id}", "Operation:residentRequests");
$route->post("/requests", "Operation:residentRequests");
$route->post("/requests/{id}", "Operation:residentRequests");
$route->get("/orcamentos", "Operation:quotes");
$route->get("/orcamentos/{id}", "Operation:quotes");
$route->post("/orcamentos", "Operation:quotes");
$route->post("/orcamentos/{id}", "Operation:quotes");
$route->get("/quotes", "Operation:quotes");
$route->get("/quotes/{id}", "Operation:quotes");
$route->post("/quotes", "Operation:quotes");
$route->post("/quotes/{id}", "Operation:quotes");
$route->get("/fornecedores", "Operation:suppliers");
$route->get("/fornecedores/{id}", "Operation:suppliers");
$route->post("/fornecedores", "Operation:suppliers");
$route->post("/fornecedores/{id}", "Operation:suppliers");
$route->get("/suppliers", "Operation:suppliers");
$route->get("/suppliers/{id}", "Operation:suppliers");
$route->post("/suppliers", "Operation:suppliers");
$route->post("/suppliers/{id}", "Operation:suppliers");
$route->get("/pessoas", "Operation:people");
$route->get("/pessoas/{id}", "Operation:people");
$route->post("/pessoas", "Operation:people");
$route->post("/pessoas/{id}", "Operation:people");
$route->get("/people", "Operation:people");
$route->get("/people/{id}", "Operation:people");
$route->post("/people", "Operation:people");
$route->post("/people/{id}", "Operation:people");
$route->get("/documentos", "Operation:documents");
$route->post("/documentos", "Operation:documents");
$route->post("/documentos/{id}", "Operation:documents");
$route->get("/relatorios", "Operation:operationReports");
$route->get("/environment/{theme}", "Operation:environment");
$route->get("/agenda", "Operation:agenda");
$route->post("/agenda", "Operation:agenda");
$route->get("/visitas", "Operation:visits");
$route->post("/visitas", "Operation:visits");
$route->get("/tickets", "ServiceDesk:tickets");
$route->post("/tickets", "ServiceDesk:tickets");
$route->get("/chamados", "ServiceDesk:tickets");
$route->post("/chamados", "ServiceDesk:tickets");
$route->get("/ops/{errcode}", "Operation:error");

$route->namespace("Source\\Controllers\\Web\\Connect");
$route->group("");
