<?php
$this->layout('_studio');
$editing = !empty($testimonial);
$published = count(array_filter($testimonials, static fn($item) => $item->status === 'published'));
$drafts = count($testimonials) - $published;
$currentRating = min(5, max(1, (int)($testimonial->rating ?? 5)));
?>
<section class="studio-page-head"><div><small>CONTEÚDO DO SITE</small><h2>Depoimentos</h2><p>Cadastre relatos, avaliações e fotos exibidas na Home e na página comercial.</p></div><?php if($editing):?><a class="studio-btn" href="<?= url('/studio/testimonials') ?>"><ion-icon name="add-outline"></ion-icon>Novo depoimento</a><?php endif;?></section>
<section class="studio-stats studio-testimonial-stats"><article><span>Total</span><strong><?= count($testimonials) ?></strong><small>Depoimentos cadastrados</small></article><article><span>Publicados</span><strong><?= $published ?></strong><small>Visíveis no site</small></article><article><span>Rascunhos</span><strong><?= $drafts ?></strong><small>Aguardando publicação</small></article></section>
<div class="studio-testimonial-layout">
  <section class="studio-panel studio-testimonial-compose"><header><div><small><?= $editing?'EDIÇÃO':'NOVO DEPOIMENTO' ?></small><h2><?= $editing?'Editar depoimento':'Cadastrar depoimento' ?></h2><p>A foto pode ser enviada ou escolhida na biblioteca.</p></div><ion-icon name="chatbox-ellipses-outline"></ion-icon></header>
    <form class="studio-form" action="<?= $editing?url('/studio/testimonials/'.$testimonial->id):url('/studio/testimonials') ?>" method="post" enctype="multipart/form-data"><?= csrf_input() ?><input type="hidden" name="action" value="save">
      <div class="studio-fields-two"><label>Nome da pessoa *<input name="title" maxlength="180" value="<?= htmlspecialchars($testimonial->title??'') ?>" required></label><label>Condomínio ou empresa<input name="townhouse" maxlength="180" value="<?= htmlspecialchars($testimonial->townhouse??'') ?>"></label></div>
      <label>Depoimento *<textarea name="content" rows="7" minlength="10" required><?= htmlspecialchars($testimonial->content??'') ?></textarea></label>
      <fieldset class="studio-rating-field"><legend>Avaliação</legend><div><?php for($rating=5;$rating>=1;$rating--):?><input type="radio" id="testimonial-rating-<?= $rating ?>" name="rating" value="<?= $rating ?>" <?= $currentRating===$rating?'checked':'' ?>><label for="testimonial-rating-<?= $rating ?>" title="<?= $rating ?> estrela<?= $rating===1?'':'s' ?>">★</label><?php endfor;?></div><small>Selecione de 1 a 5 estrelas.</small></fieldset>
      <div class="studio-fields-two"><label>Status<select name="status"><option value="published" <?= ($testimonial->status??'draft')==='published'?'selected':'' ?>>Publicado</option><option value="draft" <?= ($testimonial->status??'draft')==='draft'?'selected':'' ?>>Rascunho</option></select></label><label>Enviar nova foto<input type="file" name="cover" accept="image/jpeg,image/png,image/webp"></label></div>
      <label>Foto da biblioteca<input id="testimonial-library-cover" name="library_cover" value="<?= htmlspecialchars($testimonial->cover??'') ?>" placeholder="Selecione uma imagem"><button class="studio-btn studio-media-pick" type="button" data-media-picker data-media-target="#testimonial-library-cover"><ion-icon name="images-outline"></ion-icon>Escolher na biblioteca</button></label>
      <div class="studio-form-actions"><?php if($editing):?><button class="studio-btn danger" type="submit" name="action" value="delete" onclick="return confirm('Excluir este depoimento?')"><ion-icon name="trash-outline"></ion-icon>Excluir</button><?php endif;?><button class="studio-btn primary" type="submit"><ion-icon name="save-outline"></ion-icon><?= $editing?'Salvar alterações':'Cadastrar depoimento' ?></button></div>
    </form>
  </section>
  <section class="studio-panel studio-testimonial-list"><header><div><small>SITE</small><h2>Depoimentos cadastrados</h2><p>Somente os publicados aparecem para o público.</p></div><span><?= count($testimonials) ?></span></header><div><?php if(!$testimonials):?><div class="studio-empty">Nenhum depoimento cadastrado.</div><?php endif;?><?php foreach($testimonials as $item):?><article><img src="<?= $item->cover?image($item->cover,160,160):themeStudio('/assets/images/avatar.jpg','moves_studio') ?>" alt=""><div><header><strong><?= htmlspecialchars($item->title) ?></strong><span class="status <?= $item->status==='published'?'post':'draft' ?>"><?= $item->status==='published'?'Publicado':'Rascunho' ?></span></header><div class="studio-rating-read" aria-label="<?= (int)($item->rating??5) ?> de 5 estrelas"><?= str_repeat('★',min(5,max(1,(int)($item->rating??5)))) ?></div><small><?= htmlspecialchars($item->townhouse?:'Sem identificação adicional') ?></small><p><?= htmlspecialchars(mb_strimwidth(strip_tags($item->content),0,150,'...')) ?></p></div><a class="studio-icon-btn" href="<?= url('/studio/testimonials/'.$item->id) ?>" title="Editar"><ion-icon name="create-outline"></ion-icon></a></article><?php endforeach;?></div></section>
</div>
