/** Organic UI v2 - Data table: sort, filter, select, pagination */
const instances=new WeakMap();
function cellValue(cell){return (cell?.dataset.orgSortValue??cell?.textContent??'').trim()}
function compare(a,b,type){if(type==='number'){const n=x=>Number(cellValue(x).replace(/[^0-9,.-]/g,'').replace(',','.'))||0;return n(a)-n(b)}if(type==='date')return new Date(cellValue(a))-new Date(cellValue(b));return cellValue(a).localeCompare(cellValue(b),undefined,{numeric:true,sensitivity:'base'})}
class OrganicTable{
 constructor(table){this.table=table;this.body=table.tBodies[0];if(!this.body)return;this.allRows=[...this.body.rows];this.filteredRows=[...this.allRows];this.page=1;this.pageSize=Number(table.dataset.orgTablePageSize||0);instances.set(table,this);this.bind();this.refresh()}
 bind(){this.table.querySelectorAll('[data-org-sort]').forEach(btn=>btn.addEventListener('click',()=>this.sort(btn)));const master=this.table.querySelector('[data-org-table-select-all]');this.master=master;this.rowsChecks=[...this.table.querySelectorAll('[data-org-table-select-row]')];this.rowsChecks.forEach(c=>c.addEventListener('change',()=>this.updateSelection()));master?.addEventListener('change',()=>{this.rowsChecks.forEach(c=>{if(!c.closest('tr')?.hidden)c.checked=master.checked});this.updateSelection()});const sel=document.querySelector(`[data-org-table-page-size="#${CSS.escape(this.table.id)}"]`);sel?.addEventListener('change',()=>{this.pageSize=Number(sel.value||0);this.page=1;this.refresh()})}
 sort(btn){const th=btn.closest('th'),index=[...th.parentNode.children].indexOf(th),dir=btn.getAttribute('aria-sort')==='ascending'?'descending':'ascending';this.table.querySelectorAll('[data-org-sort]').forEach(b=>b.removeAttribute('aria-sort'));btn.setAttribute('aria-sort',dir);this.allRows.sort((a,b)=>compare(a.cells[index],b.cells[index],btn.dataset.orgSort)*(dir==='ascending'?1:-1));this.applyFilter(this.query||'')}
 applyFilter(q=''){this.query=q.trim().toLowerCase();this.filteredRows=this.allRows.filter(r=>!this.query||r.textContent.toLowerCase().includes(this.query));this.page=1;this.refresh();this.table.dispatchEvent(new CustomEvent('organic:table:filter',{bubbles:true,detail:{query:this.query,results:this.filteredRows.length}}))}
 setPage(page){const pages=this.pages();this.page=Math.max(1,Math.min(Number(page)||1,pages));this.refresh();this.table.dispatchEvent(new CustomEvent('organic:table:page',{bubbles:true,detail:{page:this.page,pages}}))}
 pages(){return this.pageSize?Math.max(1,Math.ceil(this.filteredRows.length/this.pageSize)):1}
 refresh(){this.allRows.forEach(r=>{r.hidden=true});const start=this.pageSize?(this.page-1)*this.pageSize:0,end=this.pageSize?start+this.pageSize:this.filteredRows.length;this.filteredRows.slice(start,end).forEach(r=>{r.hidden=false;this.body.appendChild(r)});this.renderPager();this.updateSelection()}
 renderPager(){const sel=`[data-org-table-pagination="#${CSS.escape(this.table.id)}"]`;document.querySelectorAll(sel).forEach(p=>{const pages=this.pages();p.innerHTML='';if(!this.pageSize||pages<=1)return;const mk=(label,page,disabled=false,active=false)=>{const b=document.createElement('button');b.type='button';b.className='org-pagination-item';b.textContent=label;b.disabled=disabled;b.classList.toggle('is-active',active);b.setAttribute('aria-current',active?'page':'false');b.addEventListener('click',()=>this.setPage(page));return b};p.append(mk('‹',this.page-1,this.page===1));for(let i=1;i<=pages;i++)p.append(mk(String(i),i,false,i===this.page));p.append(mk('›',this.page+1,this.page===pages))})}
 updateSelection(){this.rowsChecks.forEach(c=>c.closest('tr')?.classList.toggle('org-table-row-selected',c.checked));const visible=this.rowsChecks.filter(c=>!c.closest('tr')?.hidden);if(this.master){this.master.checked=visible.length>0&&visible.every(c=>c.checked);this.master.indeterminate=visible.some(c=>c.checked)&&!this.master.checked}const selected=this.rowsChecks.filter(c=>c.checked);this.table.dispatchEvent(new CustomEvent('organic:table-selection',{bubbles:true,detail:{selected:selected.length,rows:selected.map(c=>c.closest('tr'))}}))}
}
function init(table){if(instances.has(table))return instances.get(table);return new OrganicTable(table)}
document.querySelectorAll('[data-org-table]').forEach(init);
document.addEventListener('input',e=>{const input=e.target.closest('[data-org-table-filter]');if(!input)return;const table=document.querySelector(input.dataset.orgTableFilter);if(table)init(table).applyFilter(input.value)});
window.Organic=window.Organic||{};window.Organic.Table={init,get:t=>instances.get(typeof t==='string'?document.querySelector(t):t),filter:(t,q)=>{const el=typeof t==='string'?document.querySelector(t):t;init(el)?.applyFilter(q)},page:(t,p)=>{const el=typeof t==='string'?document.querySelector(t):t;init(el)?.setPage(p)}};
