/** Organic UI v2 - Toast queue/positions/API */
const timers=new WeakMap();let defaults={position:'top-right',duration:4000,max:5};
function region(position=defaults.position){let el=document.querySelector(`[data-org-toast-region="${position}"]`);if(!el){el=document.createElement('div');el.className=`org-toast-region org-toast-region-${position}`;el.dataset.orgToastRegion=position;el.setAttribute('aria-live','polite');el.setAttribute('aria-atomic','false');document.body.appendChild(el)}return el}
function close(t){if(!t||t.classList.contains('is-closing'))return;t.classList.add('is-closing');clearTimeout(timers.get(t));setTimeout(()=>{t.remove();t.dispatchEvent(new CustomEvent('organic:toast:close'))},200)}
function show(options={}){const o=typeof options==='string'?{message:options}:options,type=o.type||'info',r=region(o.position||defaults.position);while(r.children.length>=Number(o.max||defaults.max))close(r.firstElementChild);const t=document.createElement('div');t.className=`org-toast org-toast-${type}`;t.dataset.orgToast='';t.setAttribute('role',type==='danger'?'alert':'status');const content=document.createElement('div');content.className='org-toast-content';const title=document.createElement('strong');title.className='org-toast-title';title.textContent=o.title||({success:'Sucesso',danger:'Erro',warning:'Atenção',info:'Informação',primary:'Organic'}[type]||'Organic');const text=document.createElement('div');text.className='org-toast-text';text.textContent=o.message||'';const b=document.createElement('button');b.className='org-toast-close';b.type='button';b.dataset.orgToastClose='';b.ariaLabel='Fechar';b.textContent='×';content.append(title,text);t.append(content,b);if(o.action){const a=document.createElement('button');a.type='button';a.className='org-toast-action';a.textContent=o.action.label||'Ação';a.addEventListener('click',()=>o.action.onClick?.(t));t.append(a)}r.appendChild(t);const d=Number(o.duration??defaults.duration);if(d>0)timers.set(t,setTimeout(()=>close(t),d));t.dispatchEvent(new CustomEvent('organic:toast:open'));return t}
document.addEventListener('click',e=>{const b=e.target.closest('[data-org-toast-close]');if(b)close(b.closest('[data-org-toast]'))});
function clear(position){const roots=position?[region(position)]:[...document.querySelectorAll('[data-org-toast-region]')];roots.forEach(r=>[...r.children].forEach(close))}
function configure(o={}){defaults={...defaults,...o};return {...defaults}}
window.Organic=window.Organic||{};window.Organic.Toast={show,close,clear,configure,success:(m,o={})=>show({...o,message:m,type:'success'}),error:(m,o={})=>show({...o,message:m,type:'danger'}),warning:(m,o={})=>show({...o,message:m,type:'warning'}),info:(m,o={})=>show({...o,message:m,type:'info'}),primary:(m,o={})=>show({...o,message:m,type:'primary'})};
