<?php
$this->layout('layouts/studio');
$products=['web'=>['Web','globe-outline'],'app'=>['App','phone-portrait-outline'],'studio'=>['Studio','studio-logo-outline-white.svg'],'erp'=>['ERP','business-outline'],'support'=>['Suporte','help-buoy-outline']];
$current=null;
foreach($versions as $candidate){if($candidate->status==='current'){$current=$candidate;break;}}
?>
<section class="studio-page-header"><div><p class="studio-eyebrow">Sistema</p><h1 class="studio-page-title">Versões do MovesOS</h1><p class="studio-page-description">Históricos independentes para Web, App, Studio, ERP e Suporte.</p></div><?php if($current):?><div class="studio-page-actions"><span class="studio-version-current studio-badge primary"><ion-icon name="git-branch-outline"></ion-icon><?= $products[$product][0] ?> atual <strong><?= htmlspecialchars($current->version) ?></strong></span></div><?php endif;?></section>
<nav class="studio-product-tabs" aria-label="Produtos do MovesOS"><?php foreach($products as $slug=>[$label,$icon]):?><a class="<?= $product===$slug?'active':'' ?>" href="<?= url($adminBase . '/versions?product='.$slug) ?>"><?php if($slug==='studio'):?><img class="studio-product-logo" src="<?= themeStudio('/assets/images/'.$icon,'default') ?>" alt=""><?php else:?><ion-icon name="<?= $icon ?>"></ion-icon><?php endif;?><span><?= $label ?><small>v<?= htmlspecialchars($currentVersions[$slug]??'—') ?></small></span></a><?php endforeach;?></nav>
<div class="studio-version-grid">
    <section class="studio-panel studio-version-compose"><header><div><small>NOVA VERSÃO · <?= strtoupper($products[$product][0]) ?></small><h2>Publicar versão</h2><p>A publicação altera somente o histórico deste produto.</p></div><?php if($product==='studio'):?><img class="studio-version-logo" src="<?= themeStudio('/assets/images/studio-logo-outline-white.svg','default') ?>" alt="MovesOS Studio"><?php else:?><ion-icon name="<?= $products[$product][1] ?>"></ion-icon><?php endif;?></header><form class="studio-form" action="<?= url($adminBase . '/versions?product='.$product) ?>" method="post"><?= csrf_input() ?><input type="hidden" name="action" value="release"><input type="hidden" name="product" value="<?= $product ?>"><div class="studio-fields-two"><label>Número da versão<input name="version" placeholder="1.1.0" pattern="[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?" required></label><label>Nome da entrega<input name="name" maxlength="120" placeholder="Ex.: Biblioteca inteligente" required></label></div><label>Notas da versão<textarea name="notes" rows="7" minlength="10" placeholder="Descreva as melhorias, correções e mudanças importantes..." required></textarea></label><button class="studio-btn primary" type="submit"><ion-icon name="cloud-upload-outline"></ion-icon>Publicar versão de <?= $products[$product][0] ?></button></form></section>
    <section class="studio-panel studio-version-history"><header><div><small>HISTÓRICO · <?= strtoupper($products[$product][0]) ?></small><h2>Versões publicadas</h2></div><span><?= count($versions) ?></span></header><div><?php if(!$versions):?><div class="studio-empty">Nenhuma versão cadastrada para este produto.</div><?php endif;?><?php foreach($versions as $version):?><article class="<?= $version->status==='current'?'current':'' ?>"><i><ion-icon name="<?= $version->status==='current'?'checkmark-circle':'git-commit-outline' ?>"></ion-icon></i><div><header><strong>v<?= htmlspecialchars($version->version) ?> · <?= htmlspecialchars($version->name?:'Sem nome') ?></strong><span><?= $version->status==='current'?'Atual':'Arquivada' ?></span></header><p><?= nl2br(htmlspecialchars($version->notes?:'Sem notas.')) ?></p><small><?= date_fmt($version->published_at,'d/m/Y H:i') ?> · <?= htmlspecialchars($version->author_name?:'Sistema') ?></small></div></article><?php endforeach;?></div></section>
</div>
