<?php $this->layout('layouts/studio'); ?>
<?php
$pageUrl=function(int $target) use($tab,$period,$dateFrom,$dateTo,$search,$statusFilter,$actionFilter,$severityFilter){return url('/studio/notifications?'.http_build_query(array_filter(['tab'=>$tab,'page'=>$target,'period'=>$period,'date_from'=>$dateFrom,'date_to'=>$dateTo,'q'=>$search,'status'=>$statusFilter,'action'=>$actionFilter,'severity'=>$severityFilter],static fn($value)=>$value!==''&&$value!==null)));};
$renderPagination=function() use($page,$pages,$total,$pageUrl){if($pages<=1)return;?><footer class="studio-list-footer"><span><?= number_format($total,0,',','.') ?> registro(s) · Página <?= $page ?> de <?= $pages ?></span><nav class="studio-pagination"><?php if($page>1):?><a class="studio-pagination_item" href="<?= $pageUrl($page-1) ?>"><ion-icon name="arrow-back-outline"></ion-icon></a><?php endif;?><?php for($i=max(1,$page-2);$i<=min($pages,$page+2);$i++):?><a class="studio-pagination_item <?= $i===$page?'studio-pagination_active':'' ?>" href="<?= $pageUrl($i) ?>"><?= $i ?></a><?php endfor;?><?php if($page<$pages):?><a class="studio-pagination_item" href="<?= $pageUrl($page+1) ?>"><ion-icon name="arrow-forward-outline"></ion-icon></a><?php endif;?></nav></footer><?php };
$hasFilters=$search!==''||$statusFilter!==''||$actionFilter!==''||$severityFilter!==''||$dateFrom!==null||$dateTo!==null||$period!==30;
?>
<section class="studio-page-head"><div><p class="studio-eyebrow">Comunicação e auditoria</p><h1 class="studio-page-title">Central de notificações</h1><p class="studio-page-description">Envie mensagens e acompanhe cada etapa sem carregar históricos inteiros de uma vez.</p></div><?php if($unreadCount):?><form action="<?= url('/studio/notifications/read-all') ?>" method="post"><?= csrf_input() ?><button class="studio-btn" type="submit">Marcar <?= $unreadCount ?> como lida(s)</button></form><?php endif;?></section>

<nav class="studio-notification-tabs studio-tabs" aria-label="Áreas da central">
    <a class="studio-tab <?= $tab==='messages'?'active active':'' ?>" href="<?= url('/studio/notifications?tab=messages') ?>"><ion-icon name="chatbubbles-outline"></ion-icon><span>Mensagens</span><small class="studio-tab-count"><?= (int)$tabCounts['messages'] ?></small></a>
    <a class="studio-tab <?= $tab==='queue'?'active active':'' ?>" href="<?= url('/studio/notifications?tab=queue') ?>"><ion-icon name="mail-unread-outline"></ion-icon><span>Fila de envio</span><small class="studio-tab-count"><?= (int)$tabCounts['queue'] ?></small></a>
    <?php if($canAudit):?><a class="studio-tab <?= $tab==='audit'?'active active':'' ?>" href="<?= url('/studio/notifications?tab=audit') ?>"><ion-icon name="git-compare-outline"></ion-icon><span>Alterações recentes</span><small class="studio-tab-count"><?= (int)$tabCounts['audit'] ?></small></a><?php endif;?>
</nav>

<?php if($tab==='messages'):?>
<div class="studio-notification-management">
    <section class="studio-panel studio-notification-compose"><header><div><small>NOVA MENSAGEM</small><h2>Enviar comunicação</h2></div><ion-icon name="send-outline"></ion-icon></header>
        <details class="studio-notification-guide"><summary><ion-icon name="help-circle-outline"></ion-icon>Como cadastrar uma comunicação</summary><ol><li>Crie um título e escreva a mensagem.</li><li>Escolha o público e o canal.</li><li>Defina prioridade, link e agendamento.</li></ol><a href="<?= url('/suporte/comunicacao/como-cadastrar-uma-comunicacao') ?>" target="_blank">Abrir tutorial completo <ion-icon name="arrow-forward-outline"></ion-icon></a></details>
        <form class="studio-form" action="<?= url('/studio/notifications/message') ?>" method="post"><?= csrf_input() ?><label>Título/assunto *<input name="title" maxlength="255" required placeholder="Ex.: Manutenção programada"></label><label>Mensagem *<textarea name="body" rows="5" required placeholder="Escreva uma mensagem clara para os usuários"></textarea></label><div class="studio-fields-two"><label>Destinatários<select name="audience" data-notification-audience><option value="all">Todos os usuários</option><option value="admins">Administradores</option><option value="master">Somente master</option><option value="user">Usuário específico</option></select></label><label>Canal de envio<select name="delivery_channels"><option value="system">Somente no sistema</option><option value="email">Somente por e-mail</option><option value="both">Sistema e e-mail</option></select></label></div><label class="notification-target-user">Usuário<select name="target_user_id"><option value="">Selecione</option><?php foreach($users as $item):?><option value="<?= $item->id ?>"><?= htmlspecialchars($item->fullName().' — '.$item->email) ?></option><?php endforeach;?></select></label><div class="studio-fields-two"><label>Prioridade<select name="severity"><option value="info">Informação</option><option value="success">Sucesso</option><option value="warning">Atenção</option><option value="error">Urgente</option></select></label><label>Link ao clicar<input name="link" placeholder="<?= url('/studio/dash') ?>"></label></div><div class="studio-fields-two"><label>Agendar para<input type="datetime-local" name="scheduled_at"><small>Vazio para preparar agora.</small></label><label>Expirar em<input type="datetime-local" name="expires_at"><small>Aplicável à notificação interna.</small></label></div><button class="studio-btn primary" type="submit"><ion-icon name="send-outline"></ion-icon>Enviar ou agendar</button></form>
    </section>
    <section class="studio-panel studio-message-history"><header><div><small>HISTÓRICO</small><h2>Mensagens cadastradas</h2></div><span><?= number_format($total,0,',','.') ?></span></header><div class="studio-message-history-list"><?php if(!$messages):?><div class="studio-empty">Nenhuma mensagem cadastrada.</div><?php endif;?><?php foreach($messages as $item):?><article><i class="<?= htmlspecialchars($item->severity) ?>"><ion-icon name="<?= $item->status==='scheduled'?'time-outline':'checkmark-circle-outline' ?>"></ion-icon></i><div><strong><?= htmlspecialchars($item->title) ?></strong><p><?= htmlspecialchars($item->body) ?></p><small><?= $item->status==='scheduled'?'Agendada para '.date_fmt($item->scheduled_at):'Preparada em '.date_fmt($item->delivered_at?:$item->created_at) ?> · <?= htmlspecialchars($item->audience) ?> · <?= ['system'=>'Sistema','email'=>'E-mail','both'=>'Sistema + e-mail'][$item->delivery_channels??'system'] ?></small></div><span class="status <?= $item->status==='sent'?'post':'draft' ?>"><?= $item->status==='sent'?'Preparada':'Agendada' ?></span></article><?php endforeach;?></div><?php $renderPagination(); ?></section>
</div>
<?php endif;?>

<?php if(in_array($tab,['queue','audit'],true)):?>
<section class="studio-filter-toolbar">
    <div><strong><?= $tab==='queue'?'Fila de envio':'Alterações recentes' ?></strong><small><?= $hasFilters?'A lista está usando filtros personalizados.':'Exibindo os registros dos últimos 30 dias.' ?></small></div>
    <button class="studio-btn primary" type="button" data-filter-open><ion-icon name="filter-outline"></ion-icon>Filtrar<?php if($hasFilters):?><span class="studio-filter-active-dot" aria-label="Filtros ativos"></span><?php endif;?></button>
</section>
<div class="studio-filter-drawer" data-filter-drawer aria-hidden="true">
    <button class="studio-filter-backdrop" type="button" data-filter-close aria-label="Fechar filtros"></button>
    <aside class="studio-filter-sheet" role="dialog" aria-modal="true" aria-labelledby="notification-filter-title">
        <header><div><small>FILTROS</small><h2 id="notification-filter-title">Filtrar registros</h2><p><?= $tab==='queue'?'Encontre envios por status, destinatário e período.':'Encontre alterações por ação, prioridade e período.' ?></p></div><button type="button" data-filter-close aria-label="Fechar filtros"><ion-icon name="close-outline"></ion-icon></button></header>
    <form class="studio-pill-filter studio-pill-filter-drawer ajax_off" method="get" action="<?= url('/studio/notifications') ?>"><input type="hidden" name="tab" value="<?= $tab ?>"><label class="studio-filter-search">Pesquisar<input name="q" value="<?= htmlspecialchars($search) ?>" placeholder="<?= $tab==='queue'?'Destinatário, e-mail ou assunto':'Descrição, área ou registro' ?>"></label>
        <?php if($tab==='queue'):?><fieldset><legend>Status</legend><div><?php foreach([''=>'Todos','pending'=>'Pendente','processing'=>'Processando','retry'=>'Nova tentativa','sent'=>'Enviado','failed'=>'Falhou','cancelled'=>'Cancelado'] as $value=>$label):?><label><input type="radio" name="status" value="<?= $value ?>" <?= $statusFilter===$value?'checked':'' ?>><span><?= $label ?></span></label><?php endforeach;?></div></fieldset><?php else:?><fieldset><legend>Ação</legend><div><?php foreach([''=>'Todas','create'=>'Criação','update'=>'Atualização','delete'=>'Exclusão','login'=>'Entrada','logout'=>'Saída'] as $value=>$label):?><label><input type="radio" name="action" value="<?= $value ?>" <?= $actionFilter===$value?'checked':'' ?>><span><?= $label ?></span></label><?php endforeach;?></div></fieldset><fieldset><legend>Prioridade</legend><div><?php foreach([''=>'Todas','info'=>'Informação','warning'=>'Atenção','error'=>'Erro'] as $value=>$label):?><label><input type="radio" name="severity" value="<?= $value ?>" <?= $severityFilter===$value?'checked':'' ?>><span><?= $label ?></span></label><?php endforeach;?></div></fieldset><?php endif;?>
        <fieldset><legend>Períodos predefinidos</legend><div><?php foreach([1=>'Hoje',7=>'7 dias',15=>'15 dias',30=>'30 dias',60=>'60 dias'] as $value=>$label):?><label><input type="radio" name="period" value="<?= $value ?>" <?= !$dateFrom&&!$dateTo&&$period===$value?'checked':'' ?>><span><?= $label ?></span></label><?php endforeach;?></div></fieldset>
        <fieldset class="studio-custom-period"><legend>Período específico</legend><p>Escolha uma data inicial e uma data final.</p><div class="studio-date-range"><label>Data inicial<input type="date" name="date_from" value="<?= htmlspecialchars((string)$dateFrom) ?>"></label><span>até</span><label>Data final<input type="date" name="date_to" value="<?= htmlspecialchars((string)$dateTo) ?>"></label></div></fieldset>
        <footer><a class="studio-btn" href="<?= url('/studio/notifications?tab='.$tab) ?>">Limpar</a><button class="studio-btn primary" type="submit"><ion-icon name="filter-outline"></ion-icon>Aplicar filtros</button></footer>
    </form>
    </aside>
</div>
<?php endif;?>

<?php if($tab==='queue'):?><section class="studio-panel studio-mail-queue studio-tabular-panel"><header><div><small>E-MAIL</small><h2>Fila de envio</h2></div><span class="studio-counter"><?= number_format($total,0,',','.') ?> resultado(s)</span></header><div class="studio-table-wrap"><table class="studio-table"><thead><tr><th>Destinatário</th><th>Assunto</th><th>Agendamento</th><th>Tentativas</th><th>Status</th><th></th></tr></thead><tbody><?php if(!$mailQueue):?><tr><td colspan="6">Nenhum envio corresponde aos filtros.</td></tr><?php endif;?><?php foreach($mailQueue as $mail):?><?php $mailStatus=['pending'=>'Pendente','processing'=>'Processando','retry'=>'Nova tentativa','sent'=>'Enviado','failed'=>'Falhou','cancelled'=>'Cancelado'][$mail->status]??ucfirst($mail->status);?><tr><td><strong><?= htmlspecialchars($mail->recipient_name) ?></strong><small><?= htmlspecialchars($mail->recipient_email) ?></small></td><td><?= htmlspecialchars($mail->subject) ?><?php if($mail->error_message):?><small class="studio-mail-error"><?= htmlspecialchars(mb_strimwidth($mail->error_message,0,75,'...')) ?></small><?php endif;?></td><td><?= date_fmt($mail->scheduled_at?:$mail->created_at) ?></td><td><?= (int)$mail->attempts ?>/<?= (int)$mail->max_attempts ?></td><td><span class="mail-status <?= htmlspecialchars($mail->status) ?>"><?= $mailStatus ?></span></td><td><div class="studio-mail-actions"><?php if(!in_array($mail->status,['sent','cancelled'],true)):?><form action="<?= url('/studio/notifications/mail-queue') ?>" method="post"><?= csrf_input() ?><input type="hidden" name="queue_id" value="<?= $mail->id ?>"><button name="action" value="cancel" title="Cancelar"><ion-icon name="close-circle-outline"></ion-icon></button></form><?php endif;?><?php if(in_array($mail->status,['failed','cancelled','retry'],true)):?><form action="<?= url('/studio/notifications/mail-queue') ?>" method="post"><?= csrf_input() ?><input type="hidden" name="queue_id" value="<?= $mail->id ?>"><button name="action" value="retry" title="Tentar novamente"><ion-icon name="refresh-outline"></ion-icon></button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div><?php $renderPagination(); ?><footer class="studio-mail-queue-help"><ion-icon name="information-circle-outline"></ion-icon>Falhas recebem novas tentativas automáticas.</footer></section><?php endif;?>

<?php if($tab==='audit'&&$canAudit):?><section class="studio-panel studio-audit-log studio-tabular-panel"><header><div><small>RASTREABILIDADE</small><h2>Alterações recentes no sistema</h2></div><span><?= number_format($total,0,',','.') ?> resultado(s)</span></header><div class="studio-table-wrap"><table class="studio-table"><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Área</th><th>Registro</th><th>Detalhes</th><th>IP</th></tr></thead><tbody><?php if(!$auditLogs):?><tr><td colspan="7">Nenhuma alteração corresponde aos filtros.</td></tr><?php endif;?><?php foreach($auditLogs as $log):?><?php $context=json_decode((string)$log->context_json,true);?><tr><td><?= date_fmt($log->created_at) ?></td><td><?= htmlspecialchars($userMap[$log->users_id]??'Sistema') ?></td><td><span class="audit-action <?= htmlspecialchars($log->action) ?>"><?= htmlspecialchars($log->action) ?></span></td><td><?= htmlspecialchars($log->entity) ?></td><td>#<?= htmlspecialchars((string)$log->entity_id) ?></td><td><?= htmlspecialchars(implode(', ',$context['changed_fields']??[]))?:'—' ?></td><td><?= htmlspecialchars((string)$log->ip)?:'—' ?></td></tr><?php endforeach;?></tbody></table></div><?php $renderPagination(); ?></section><?php endif;?>
<?php $this->start('scripts') ?><script>
document.querySelector('[data-notification-audience]')?.addEventListener('change',e=>document.querySelector('.notification-target-user')?.classList.toggle('show',e.target.value==='user'));
const studioFilterDrawer=document.querySelector('[data-filter-drawer]');
const studioToggleFilter=open=>{if(!studioFilterDrawer)return;studioFilterDrawer.classList.toggle('open',open);studioFilterDrawer.setAttribute('aria-hidden',open?'false':'true');document.body.classList.toggle('studio-filter-open',open);if(open)studioFilterDrawer.querySelector('input,button')?.focus()};
document.querySelector('[data-filter-open]')?.addEventListener('click',()=>studioToggleFilter(true));
studioFilterDrawer?.querySelectorAll('[data-filter-close]').forEach(button=>button.addEventListener('click',()=>studioToggleFilter(false)));
const studioDateInputs=studioFilterDrawer?.querySelectorAll('.studio-date-range input[type="date"]')||[];
const studioPeriodInputs=studioFilterDrawer?.querySelectorAll('input[name="period"]')||[];
studioDateInputs.forEach(input=>{input.addEventListener('change',()=>studioPeriodInputs.forEach(period=>period.checked=false));input.addEventListener('click',()=>{if(typeof input.showPicker==='function')input.showPicker()})});
studioPeriodInputs.forEach(period=>period.addEventListener('change',()=>{if(!period.checked)return;studioDateInputs.forEach(input=>input.value='')}));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&studioFilterDrawer?.classList.contains('open'))studioToggleFilter(false)});
</script><?php $this->stop() ?>
