<?php $this->layout('layouts/studio'); ?>
<?php $total = count($pages) + count($posts) + count($categories) + count($users) + count($proposals); ?>
<section class="studio-page-header"><div><small>BUSCA GERAL</small><h2><?= $term !== '' ? 'Resultados para “'.htmlspecialchars($term).'”' : 'Buscar no Studio' ?></h2><p><?= $term !== '' ? $total.' resultado(s) encontrado(s).' : 'Digite no campo acima para localizar conteúdos e usuários.' ?></p></div></section>
<?php if ($term !== '' && !$total): ?><div class="studio-empty">Nenhum resultado encontrado. Tente outro termo.</div><?php endif; ?>
<div class="studio-search-results">
    <?php if ($pages): ?><section class="studio-panel"><header><div><small>CONTEÚDO</small><h2>Páginas</h2></div><span><?= count($pages) ?></span></header><?php foreach ($pages as $item): ?><a href="<?= url('/operation/page/'.$item->id) ?>"><ion-icon name="document-text-outline"></ion-icon><span><strong><?= htmlspecialchars($item->title) ?></strong><small>/<?= htmlspecialchars($item->uri) ?></small></span><ion-icon name="chevron-forward-outline"></ion-icon></a><?php endforeach; ?></section><?php endif; ?>
    <?php if ($posts): ?><section class="studio-panel"><header><div><small>CONTEÚDO</small><h2>Artigos</h2></div><span><?= count($posts) ?></span></header><?php foreach ($posts as $item): ?><a href="<?= url('/operation/blog/post/'.$item->id) ?>"><ion-icon name="newspaper-outline"></ion-icon><span><strong><?= htmlspecialchars($item->title) ?></strong><small><?= htmlspecialchars((string)$item->subtitle) ?></small></span><ion-icon name="chevron-forward-outline"></ion-icon></a><?php endforeach; ?></section><?php endif; ?>
    <?php if ($categories): ?><section class="studio-panel"><header><div><small>ORGANIZAÇÃO</small><h2>Categorias</h2></div><span><?= count($categories) ?></span></header><?php foreach ($categories as $item): ?><a href="<?= url('/operation/blog/category/'.$item->id) ?>"><ion-icon name="folder-open-outline"></ion-icon><span><strong><?= htmlspecialchars($item->title) ?></strong><small><?= htmlspecialchars((string)$item->description) ?></small></span><ion-icon name="chevron-forward-outline"></ion-icon></a><?php endforeach; ?></section><?php endif; ?>
    <?php if ($users): ?><section class="studio-panel"><header><div><small>GESTÃO</small><h2>Usuários</h2></div><span><?= count($users) ?></span></header><?php foreach ($users as $item): ?><a href="<?= url('/operation/users') ?>"><ion-icon name="person-circle-outline"></ion-icon><span><strong><?= htmlspecialchars($item->fullName()) ?></strong><small><?= htmlspecialchars($item->email) ?></small></span><ion-icon name="chevron-forward-outline"></ion-icon></a><?php endforeach; ?></section><?php endif; ?>
    <?php if ($proposals): ?><section class="studio-panel"><header><div><small>COMERCIAL</small><h2>Propostas</h2></div><span><?= count($proposals) ?></span></header><?php foreach ($proposals as $item): ?><a href="<?= url('/operation/proposals/'.$item->id) ?>"><ion-icon name="document-text-outline"></ion-icon><span><strong><?= htmlspecialchars($item->condominium) ?></strong><small><?= htmlspecialchars($item->name.' · '.$item->protocol) ?></small></span><ion-icon name="chevron-forward-outline"></ion-icon></a><?php endforeach; ?></section><?php endif; ?>
</div>
