<?php $this->layout('layouts/studio'); $editing=!empty($record); ?>
<section class="studio-page-header operation-resource-header"><div><small>CONNECT OPERAÇÕES</small><h2><?= htmlspecialchars($config['title']) ?></h2><p>Dados operacionais compartilhados e atualizados em tempo real.</p></div><button class="studio-btn primary" type="button" data-resource-new><ion-icon name="add-outline"></ion-icon>Novo <?= htmlspecialchars(mb_strtolower($config['singular'])) ?></button></section>
<div class="operation-resource-grid">
 <section class="studio-panel operation-resource-list"><header><div><small>REGISTROS</small><h2><?= $totalItems ?> encontrado(s)</h2></div><form class="operation-resource-search" method="get" action="<?= url('/operation/'.$resource) ?>"><ion-icon name="search-outline"></ion-icon><input type="search" name="q" value="<?= htmlspecialchars($filters['q']) ?>" placeholder="Pesquisar no banco"><button class="studio-btn" aria-label="Pesquisar"><ion-icon name="arrow-forward-outline"></ion-icon></button></form></header>
  <form class="operation-resource-filters" method="get" action="<?= url('/operation/'.$resource) ?>"><input type="hidden" name="q" value="<?= htmlspecialchars($filters['q']) ?>"><?php if(isset($config['fields']['status'])):?><label>Status<select name="status"><option value="">Todos</option><?php foreach($config['fields']['status']['options'] as $value=>$label):?><option value="<?= $value ?>" <?= $filters['status']===$value?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach;?></select></label><?php endif;?><?php if(isset($config['fields']['priority'])):?><label>Prioridade<select name="priority"><option value="">Todas</option><?php foreach($config['fields']['priority']['options'] as $value=>$label):?><option value="<?= $value ?>" <?= $filters['priority']===$value?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach;?></select></label><?php endif;?><?php if(isset($config['fields']['condominium_id'])):?><label>Condomínio<select name="condominium_id"><option value="">Todos</option><?php foreach($condominiums as $option):?><option value="<?= $option->id ?>" <?= $filters['condominium_id']==$option->id?'selected':'' ?>><?= htmlspecialchars($option->name) ?></option><?php endforeach;?></select></label><?php endif;?><?php if(isset($config['fields']['assigned_to'])):?><label>Responsável<select name="assigned_to"><option value="">Todos</option><?php foreach($users as $option):?><option value="<?= $option->id ?>" <?= $filters['assigned_to']==$option->id?'selected':'' ?>><?= htmlspecialchars($option->name) ?></option><?php endforeach;?></select></label><?php endif;?><button class="studio-btn" type="submit"><ion-icon name="filter-outline"></ion-icon>Filtrar</button><a class="studio-btn" href="<?= url('/operation/'.$resource) ?>">Limpar</a></form>
  <div class="operation-resource-table" data-resource-list>
   <?php if(!$items): ?><div class="operation-empty"><ion-icon name="<?= $config['icon'] ?>"></ion-icon><strong>Nenhum registro ainda</strong><span>Use o botão acima para começar.</span></div><?php endif; ?>
   <?php foreach($items as $item): $primary=$item->name??$item->title??$item->trade_name??$item->legal_name??('#'.$item->id); ?><a href="<?= url('/operation/'.$resource.'/'.$item->id) ?>" data-search-value="<?= htmlspecialchars(mb_strtolower($primary.' '.($item->condominium_name??'').' '.($item->status??''))) ?>"><i><ion-icon name="<?= $config['icon'] ?>"></ion-icon></i><span><strong><?= !empty($item->protocol)?htmlspecialchars($item->protocol).' · ':'' ?><?= htmlspecialchars($primary) ?></strong><small><?= htmlspecialchars($item->condominium_name??$item->category??('Registro #'.$item->id)) ?></small></span><em><?= htmlspecialchars(str_replace('_',' ',$item->status??(isset($item->active)&&$item->active?'ativo':'inativo'))) ?></em><ion-icon name="chevron-forward-outline"></ion-icon></a><?php endforeach; ?>
  </div>
  <?php if($totalPages>1):?><nav class="operation-pagination" aria-label="Paginação"><?php $query=$_GET;for($number=1;$number<=$totalPages;$number++):$query['page']=$number;?><a class="<?= $number===$page?'active':'' ?>" href="<?= url('/operation/'.$resource).'?'.http_build_query($query) ?>"><?= $number ?></a><?php endfor;?></nav><?php endif;?>
 </section>
 <aside class="studio-panel operation-resource-form <?= $editing?'open':'' ?>" data-resource-form><header><div><small><?= $editing?'EDIÇÃO':'NOVO REGISTRO' ?></small><h2><?= htmlspecialchars($config['singular']) ?></h2></div><a href="<?= url('/operation/'.$resource) ?>" aria-label="Fechar"><ion-icon name="close-outline"></ion-icon></a></header>
  <form action="<?= url('/operation/'.$resource.($editing?'/'.$record->id:'')) ?>" method="post" class="studio-form"><?= csrf_input() ?><input type="hidden" name="action" value="save">
   <?php foreach($config['fields'] as $name=>$field): $value=$record->{$name}??($field['default']??''); if(($field['type']??'')==='datetime-local'&&$value)$value=date('Y-m-d\TH:i',strtotime($value)); ?><label><?= htmlspecialchars($field['label']) ?><?= !empty($field['required'])?' *':'' ?>
    <?php if(($field['type']??'')==='textarea'): ?><textarea name="<?= $name ?>" rows="4" <?= !empty($field['required'])?'required':'' ?>><?= htmlspecialchars((string)$value) ?></textarea>
    <?php elseif(($field['type']??'')==='select'): ?><select name="<?= $name ?>"><?php foreach($field['options'] as $optionValue=>$optionLabel): ?><option value="<?= $optionValue ?>" <?= (string)$value===(string)$optionValue?'selected':'' ?>><?= htmlspecialchars($optionLabel) ?></option><?php endforeach; ?></select>
    <?php elseif(($field['type']??'')==='condominium'): ?><select name="<?= $name ?>" required><option value="">Selecione</option><?php foreach($condominiums as $option): ?><option value="<?= $option->id ?>" <?= (int)$value===(int)$option->id?'selected':'' ?>><?= htmlspecialchars($option->name) ?></option><?php endforeach; ?></select>
    <?php elseif(($field['type']??'')==='issue'): ?><select name="<?= $name ?>" required><option value="">Selecione</option><?php foreach($issues as $option): ?><option value="<?= $option->id ?>" <?= (int)$value===(int)$option->id?'selected':'' ?>>#<?= $option->id ?> · <?= htmlspecialchars($option->title) ?></option><?php endforeach; ?></select>
    <?php elseif(($field['type']??'')==='demand'): ?><select name="<?= $name ?>"><option value="">Sem demanda relacionada</option><?php foreach($demands as $option): ?><option value="<?= $option->id ?>" <?= (int)$value===(int)$option->id?'selected':'' ?>><?= htmlspecialchars($option->protocol.' · '.$option->title) ?></option><?php endforeach; ?></select>
    <?php elseif(($field['type']??'')==='user'): ?><select name="<?= $name ?>"><option value="">Sem responsável</option><?php foreach($users as $option): ?><option value="<?= $option->id ?>" <?= (int)$value===(int)$option->id?'selected':'' ?>><?= htmlspecialchars($option->name) ?></option><?php endforeach; ?></select>
    <?php else: ?><input type="<?= $field['type']??'text' ?>" name="<?= $name ?>" value="<?= htmlspecialchars((string)$value) ?>" <?= !empty($field['required'])?'required':'' ?>><?php endif; ?>
   </label><?php endforeach; ?>
   <footer><button class="studio-btn primary" type="submit"><ion-icon name="save-outline"></ion-icon>Salvar</button><?php if($editing): ?><button class="studio-btn danger" type="submit" name="action" value="delete" data-confirm-submit="Excluir este registro? Esta ação não poderá ser desfeita."><ion-icon name="trash-outline"></ion-icon>Excluir</button><?php endif; ?></footer>
  </form>
 </aside>
</div>
<?php if($resource==='quotes'&&$editing): ?><section class="studio-panel studio-list-panel" style="margin-top:16px"><header><div><small>COMPARAÇÃO</small><h2>Fornecedores consultados</h2><p>Compare valores, validade e observações; a decisão permanece humana.</p></div></header><div class="studio-table-scroll"><table class="studio-table"><thead><tr><th>Fornecedor</th><th>Valor</th><th>Recebido</th><th>Validade</th><th>Status</th></tr></thead><tbody><?php if(!$offers): ?><tr><td colspan="5"><div class="studio-empty">Nenhuma cotação de fornecedor.</div></td></tr><?php endif; ?><?php foreach($offers as $offer): ?><tr><td><strong><?= htmlspecialchars($offer->supplier_name) ?></strong><small><?= htmlspecialchars($offer->notes??'') ?></small></td><td><?= $offer->amount!==null?'R$ '.number_format((float)$offer->amount,2,',','.'):'Aguardando' ?></td><td><?= $offer->received_at?date('d/m/Y',strtotime($offer->received_at)):'—' ?></td><td><?= $offer->valid_until?date('d/m/Y',strtotime($offer->valid_until)):'—' ?></td><td><?= htmlspecialchars($offer->status) ?></td></tr><?php endforeach; ?></tbody></table></div><form class="studio-form" method="post" action="<?= url('/operation/quotes/'.$record->id) ?>"><?= csrf_input() ?><input type="hidden" name="action" value="add_offer"><div class="studio-fields-three"><label>Fornecedor<select name="supplier_id" required><option value="">Selecione</option><?php foreach($suppliers as $supplier): ?><option value="<?= $supplier->id ?>"><?= htmlspecialchars($supplier->name) ?></option><?php endforeach; ?></select></label><label>Valor<input name="amount" inputmode="decimal" placeholder="0,00"></label><label>Recebido em<input type="datetime-local" name="received_at"></label><label>Validade<input type="date" name="offer_valid_until"></label><label>Observações<input name="offer_notes"></label></div><button class="studio-btn primary" type="submit">Adicionar cotação</button></form></section><?php endif; ?>
<?php if($editing): ?><section class="operation-record-workspace">
 <?php if($resource==='demands'):?><article class="studio-panel"><header><div><small>FLUXO OPERACIONAL</small><h2>Encaminhar demanda</h2></div></header><form class="studio-form" method="post" action="<?= url('/operation/demandas/'.$record->id) ?>"><?= csrf_input() ?><input type="hidden" name="action" value="transition"><div class="studio-grid studio-grid-2"><label>Status<select name="demand_status"><?php foreach($config['fields']['status']['options'] as $value=>$label):?><option value="<?= $value ?>" <?= $record->status===$value?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach;?></select></label><label>Prioridade<select name="demand_priority"><?php foreach($config['fields']['priority']['options'] as $value=>$label):?><option value="<?= $value ?>" <?= $record->priority===$value?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach;?></select></label><label>Responsável<select name="demand_assigned_to"><option value="">Não definido</option><?php foreach($users as $option):?><option value="<?= $option->id ?>" <?= (int)$record->assigned_to===(int)$option->id?'selected':'' ?>><?= htmlspecialchars($option->name) ?></option><?php endforeach;?></select></label></div><button class="studio-btn primary">Atualizar fluxo</button></form></article><?php endif;?>
 <article class="studio-panel"><header><div><small>COLABORAÇÃO</small><h2>Comentários</h2></div></header><form class="studio-form" method="post" action="<?= url('/operation/'.$resource.'/'.$record->id) ?>"><?= csrf_input() ?><input type="hidden" name="action" value="comment"><label>Adicionar comentário<textarea name="comment" rows="3" required></textarea></label><footer><label class="studio-check"><input type="checkbox" name="is_internal" value="1" checked> Nota interna</label><button class="studio-btn primary">Comentar</button></footer></form><div class="operation-comment-list"><?php foreach($comments as $comment):?><article><strong><?= htmlspecialchars($comment->user_name?:'Sistema') ?></strong><small><?= date_fmt($comment->created_at,'d/m/Y H:i') ?><?= $comment->is_internal?' · Interno':'' ?></small><p><?= nl2br(htmlspecialchars($comment->comment)) ?></p></article><?php endforeach;?><?php if(!$comments):?><div class="studio-empty">Nenhum comentário ainda.</div><?php endif;?></div></article>
 <article class="studio-panel"><header><div><small>ARQUIVOS</small><h2>Anexos</h2></div></header><form class="studio-form" method="post" enctype="multipart/form-data" action="<?= url('/operation/'.$resource.'/'.$record->id) ?>"><?= csrf_input() ?><input type="hidden" name="action" value="attachment"><label class="studio-upload-field"><ion-icon name="attach-outline"></ion-icon><strong>Adicionar arquivo</strong><span>Documento ou imagem relacionado ao registro</span><input type="file" name="attachment_file" required></label><button class="studio-btn primary">Enviar anexo</button></form><div class="operation-attachment-list"><?php foreach($attachments as $file):?><a target="_blank" rel="noopener" href="<?= url('/'.ltrim($file->file_path,'/')) ?>"><ion-icon name="document-attach-outline"></ion-icon><span><strong><?= htmlspecialchars($file->original_name) ?></strong><small><?= date_fmt($file->created_at,'d/m/Y H:i') ?></small></span></a><?php endforeach;?><?php if(!$attachments):?><div class="studio-empty">Nenhum anexo.</div><?php endif;?></div></article>
 <?php if($resource==='demands'):?><article class="studio-panel"><header><div><small>PLANEJAMENTO</small><h2>Tarefas vinculadas</h2></div></header><button class="studio-btn primary" type="button" data-studio-modal-open="#demand-task-modal"><ion-icon name="add-outline"></ion-icon>Criar tarefa</button><div class="operation-task-links"><?php foreach($tasks as $task):?><article><span><strong><?= htmlspecialchars($task->title) ?></strong><small><?= htmlspecialchars(str_replace('_',' ',$task->status)) ?> · <?= $task->due_at?date_fmt($task->due_at,'d/m H:i'):'Sem prazo' ?></small></span></article><?php endforeach;?><?php if(!$tasks):?><div class="studio-empty">Nenhuma tarefa vinculada.</div><?php endif;?></div></article><?php endif;?>
 <article class="studio-panel"><header><div><small>RASTREABILIDADE</small><h2>Histórico</h2></div></header><div class="operation-record-history"><?php foreach($activity as $event):?><article><i></i><span><strong><?= htmlspecialchars($event->summary) ?></strong><small><?= htmlspecialchars($event->user_name?:'Sistema') ?> · <?= date_fmt($event->created_at,'d/m/Y H:i') ?></small></span></article><?php endforeach;?><?php if(!$activity):?><div class="studio-empty">Nenhum evento registrado.</div><?php endif;?></div></article>
</section><?php endif; ?>
<?php if($editing&&$resource==='demands'):?><div class="studio-modal" id="demand-task-modal" data-studio-modal aria-hidden="true"><div class="studio-modal-dialog"><header class="studio-modal-header"><div><p class="studio-eyebrow">Demanda <?= htmlspecialchars($record->protocol) ?></p><h2 class="studio-modal-title">Criar tarefa</h2></div><button class="studio-modal-close" type="button" data-studio-modal-close aria-label="Fechar">×</button></header><form class="studio-form studio-modal-body" method="post" action="<?= url('/operation/demandas/'.$record->id) ?>"><?= csrf_input() ?><input type="hidden" name="action" value="create_task"><label>Título<input name="task_title" required minlength="3"></label><label>Descrição<textarea name="task_description" rows="4"></textarea></label><div class="studio-grid studio-grid-2"><label>Início<input type="datetime-local" name="task_starts_at"></label><label>Prazo<input type="datetime-local" name="task_due_at"></label><label>Prioridade<select name="task_priority"><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Responsável<select name="task_assigned_to"><option value="">Não definido</option><?php foreach($users as $option):?><option value="<?= $option->id ?>"><?= htmlspecialchars($option->name) ?></option><?php endforeach;?></select></label></div><footer class="studio-modal-footer"><button class="studio-btn" type="button" data-studio-modal-close>Cancelar</button><button class="studio-btn primary">Criar e vincular</button></footer></form></div></div><?php endif;?>
<?php $this->start('scripts') ?><script>const resourceForm=document.querySelector('[data-resource-form]');document.querySelector('[data-resource-new]')?.addEventListener('click',()=>resourceForm?.classList.add('open'));</script><?php $this->stop() ?>
